-- invitations_time_zone: invitations.time_zone, an IANA zone name for the slot in the invitation and reminder
-- emails (ADR 0017 section 4.7, owner decision C-53; FR-304; ADR 0008 post-freeze delta). Forward-only and
-- additive. The column is NULL on every row that exists before this migration (the emails then show UTC only),
-- so there is no backfill.
-- SQL generated by `prisma migrate diff`; only comments added.
--
-- No CHECK on the value. A zone name is validated as an IANA name by the invite DTO (zod or class-validator,
-- the backend track), and Postgres's own list (pg_timezone_names) differs from the one the runtime uses.
-- It hints at the candidate's location, so it is candidate data: erasure nulls it with the other personal
-- fields of the invitation (ADR 0004 9.5), and CS-4 hides it from CANDIDATE reads (candidate-interim.ts does
-- not list time_zone among the readable Invitation columns, so the default omit hides it).
--
-- No GRANT is needed: app_user holds its privileges on invitations at table level (audit_append_only), and a
-- table-level privilege covers a column added later.

-- AlterTable
ALTER TABLE "invitations" ADD COLUMN     "time_zone" TEXT;
