-- init: the schema from prisma/schema.prisma, plus the SQL that Prisma cannot express.
-- Generated by `prisma migrate dev --create-only`, then edited by hand (DB-03; ADR 0008 section 8;
-- FU-DB-01, FU-DB-02, FU-DB-09). Nothing else differs from what Prisma generated:
--   - Extensions pgcrypto and citext, first, before the first CITEXT column.
--   - Five identity columns: BIGSERIAL becomes BIGINT GENERATED ALWAYS AS IDENTITY.
--   - Five list columns become NOT NULL (Prisma emits scalar lists as nullable).
--   - At the end: 12 named CHECK constraints, 2 partial indexes, and the users.updated_at trigger.
-- No password and no role in this file. The app_user role is the next migration.

-- Extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

-- CreateEnum
CREATE TYPE "user_role" AS ENUM ('SUPER_ADMIN', 'RECRUITER', 'AUTHOR', 'REVIEWER');

-- CreateEnum
CREATE TYPE "difficulty" AS ENUM ('EASY', 'MEDIUM', 'HARD');

-- CreateEnum
CREATE TYPE "question_type" AS ENUM ('CODING', 'MCQ', 'SHORT_ANSWER');

-- CreateEnum
CREATE TYPE "proctor_profile" AS ENUM ('STANDARD', 'STRICT');

-- CreateEnum
CREATE TYPE "session_status" AS ENUM ('INVITED', 'OPENED', 'CONSENTED', 'VERIFIED', 'IN_PROGRESS', 'PAUSED', 'SUBMITTED', 'GRADED', 'UNDER_REVIEW', 'COMPLETED', 'EXPIRED', 'APPEALED', 'DECLINED');

-- CreateEnum
CREATE TYPE "submission_kind" AS ENUM ('RUN', 'SUBMIT');

-- CreateEnum
CREATE TYPE "media_stream" AS ENUM ('SCREEN', 'WEBCAM', 'AUDIO', 'SIDE_CAMERA', 'ROOM_SCAN');

-- CreateEnum
CREATE TYPE "severity" AS ENUM ('LOW', 'MEDIUM', 'HIGH');

-- CreateEnum
CREATE TYPE "risk_band" AS ENUM ('LOW', 'MEDIUM', 'HIGH');

-- CreateEnum
CREATE TYPE "verdict" AS ENUM ('CLEAN', 'SUSPICIOUS', 'VIOLATION');

-- CreateEnum
CREATE TYPE "flag_decision" AS ENUM ('CONFIRMED', 'DISMISSED');

-- CreateEnum
CREATE TYPE "appeal_status" AS ENUM ('OPEN', 'UPHELD', 'OVERTURNED');

-- CreateEnum
CREATE TYPE "event_type" AS ENUM ('FULLSCREEN_EXIT', 'TAB_SWITCH', 'FOCUS_LOST', 'PASTE_ATTEMPT', 'COPY_ATTEMPT', 'RIGHT_CLICK', 'DEVTOOLS_OPEN', 'SCREEN_SHARE_STOPPED', 'MULTI_MONITOR', 'VIRTUAL_CAMERA', 'NO_FACE', 'MULTIPLE_FACES', 'FACE_MISMATCH', 'GAZE_AWAY', 'PHONE_DETECTED', 'BOOK_DETECTED', 'SPEECH_DETECTED', 'MULTIPLE_VOICES', 'DISCONNECTED', 'RECONNECTED', 'PASTE_BURST', 'TYPING_ANOMALY', 'CODE_SIMILARITY', 'AI_LIKENESS', 'PROCTOR_PAUSE', 'PROCTOR_MESSAGE', 'SIDE_CAMERA_DISCONNECTED', 'SIDE_CAMERA_RECONNECTED', 'DROP_ATTEMPT', 'CUT_ATTEMPT', 'SHORTCUT_BLOCKED', 'EXTENSION_INTERFERENCE', 'FULLSCREEN_RESTORED', 'SCREEN_SHARE_RESUMED', 'PROCTOR_RESUME', 'IDLE_THEN_COMPLETE', 'DETECTOR_UNAVAILABLE', 'IDENTITY_MANUAL_REVIEW', 'RESUME_OTP_FAILED');

-- CreateEnum
CREATE TYPE "pause_reason" AS ENUM ('FULLSCREEN_EXIT', 'SCREEN_SHARE_STOPPED', 'SIDE_CAMERA_LOST', 'PROCTOR');

-- CreateEnum
CREATE TYPE "client_kind" AS ENUM ('WEB');

-- CreateEnum
CREATE TYPE "event_source" AS ENUM ('CLIENT', 'SERVER');

-- CreateEnum
CREATE TYPE "identity_check_status" AS ENUM ('PENDING', 'PASSED', 'LOW_CONFIDENCE', 'MANUAL_REVIEW', 'REVIEWED');

-- CreateEnum
CREATE TYPE "identity_review_reason" AS ENUM ('BELOW_THRESHOLD', 'NO_FACE', 'MULTIPLE_FACES', 'LIVENESS_NOT_CONFIRMED', 'MATCH_ERROR');

-- CreateEnum
CREATE TYPE "identity_manual_decision" AS ENUM ('MATCH', 'NO_MATCH', 'INCONCLUSIVE');

-- CreateEnum
CREATE TYPE "question_scoring" AS ENUM ('AUTO', 'MANUAL_PENDING', 'MANUAL');

-- CreateTable
CREATE TABLE "organizations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "retention_days" INTEGER NOT NULL DEFAULT 90,
    "settings" JSONB NOT NULL DEFAULT '{}',
    "current_consent_text_id" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "organizations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "email" CITEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "password_hash" TEXT,
    "role" "user_role" NOT NULL,
    "totp_secret_enc" TEXT,
    "totp_enabled" BOOLEAN NOT NULL DEFAULT false,
    "recovery_code_hashes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], -- DB-03 edit: NOT NULL, Prisma emits scalar lists as nullable
    "set_password_token_hash" TEXT,
    "set_password_expires_at" TIMESTAMPTZ(6),
    "failed_logins" INTEGER NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMPTZ(6),
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "family_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "revoked_at" TIMESTAMPTZ(6),
    "replaced_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, -- DB-03 edit: Prisma emits BIGSERIAL
    "org_id" UUID NOT NULL,
    "actor_id" UUID,
    "action" TEXT NOT NULL,
    "entity_type" TEXT NOT NULL,
    "entity_id" TEXT,
    "ip" INET,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "questions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "slug" TEXT NOT NULL,
    "type" "question_type" NOT NULL DEFAULT 'CODING',
    "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], -- DB-03 edit: NOT NULL, Prisma emits scalar lists as nullable
    "current_version_id" UUID,
    "is_archived" BOOLEAN NOT NULL DEFAULT false,
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "question_versions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "question_id" UUID NOT NULL,
    "version" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "statement_md" TEXT NOT NULL,
    "difficulty" "difficulty" NOT NULL,
    "allowed_languages" TEXT[] NOT NULL, -- DB-03 edit: NOT NULL, Prisma emits scalar lists as nullable
    "limits" JSONB NOT NULL DEFAULT '{"cpu_ms":2000,"wall_ms":5000,"memory_kb":262144}',
    "starter_code" JSONB NOT NULL DEFAULT '{}',
    "reference_solution" JSONB NOT NULL DEFAULT '{}',
    "answer_spec" JSONB,
    "is_published" BOOLEAN NOT NULL DEFAULT false,
    "validated_at" TIMESTAMPTZ(6),
    "validation_report" JSONB,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "question_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "test_cases" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "question_version_id" UUID NOT NULL,
    "input" TEXT NOT NULL,
    "expected_output" TEXT NOT NULL,
    "is_hidden" BOOLEAN NOT NULL DEFAULT true,
    "weight" DECIMAL(6,2) NOT NULL DEFAULT 1,
    "position" INTEGER NOT NULL,

    CONSTRAINT "test_cases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "question_variants" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "question_version_id" UUID NOT NULL,
    "params" JSONB NOT NULL,
    "rendered_statement" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "question_variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "variant_test_cases" (
    "variant_id" UUID NOT NULL,
    "test_case_id" UUID NOT NULL,
    "input" TEXT NOT NULL,
    "expected_output" TEXT NOT NULL,

    CONSTRAINT "variant_test_cases_pkey" PRIMARY KEY ("variant_id","test_case_id")
);

-- CreateTable
CREATE TABLE "ai_reference_solutions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "question_version_id" UUID NOT NULL,
    "variant_id" UUID,
    "assistant" TEXT NOT NULL,
    "model_label" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "solution_code" TEXT NOT NULL,
    "prompt_text" TEXT,
    "collected_at" TIMESTAMPTZ(6) NOT NULL,
    "collected_by" UUID NOT NULL,
    "superseded_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_reference_solutions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tests" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "duration_minutes" INTEGER NOT NULL,
    "profile" "proctor_profile" NOT NULL DEFAULT 'STANDARD',
    "pass_score" DECIMAL(6,2),
    "settings" JSONB NOT NULL DEFAULT '{}',
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "test_sections" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "test_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "time_limit_min" INTEGER,

    CONSTRAINT "test_sections_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "test_questions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "section_id" UUID NOT NULL,
    "question_version_id" UUID,
    "random_rule" JSONB,
    "points" DECIMAL(6,2) NOT NULL DEFAULT 100,
    "position" INTEGER NOT NULL,

    CONSTRAINT "test_questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "candidates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "email" CITEXT NOT NULL,
    "full_name" TEXT NOT NULL,
    "external_ref" TEXT,
    "erasure_requested_at" TIMESTAMPTZ(6),
    "erased_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "candidates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invitations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "test_id" UUID NOT NULL,
    "candidate_id" UUID NOT NULL,
    "token_hash" TEXT NOT NULL,
    "window_start" TIMESTAMPTZ(6) NOT NULL,
    "window_end" TIMESTAMPTZ(6) NOT NULL,
    "accommodations" JSONB NOT NULL DEFAULT '{}',
    "sent_at" TIMESTAMPTZ(6),
    "used_at" TIMESTAMPTZ(6),
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "invitation_id" UUID NOT NULL,
    "status" "session_status" NOT NULL DEFAULT 'INVITED',
    "hmac_key_enc" TEXT,
    "auth_epoch" INTEGER NOT NULL DEFAULT 0,
    "device_info" JSONB NOT NULL DEFAULT '{}',
    "client_kind" "client_kind" NOT NULL DEFAULT 'WEB',
    "started_at" TIMESTAMPTZ(6),
    "deadline_at" TIMESTAMPTZ(6),
    "paused_ms" BIGINT NOT NULL DEFAULT 0,
    "pause_reasons" "pause_reason"[] NOT NULL DEFAULT ARRAY[]::"pause_reason"[], -- DB-03 edit: NOT NULL, Prisma emits scalar lists as nullable
    "proctor_paused_at" TIMESTAMPTZ(6),
    "submitted_at" TIMESTAMPTZ(6),
    "total_score" DECIMAL(8,2),
    "risk_score" INTEGER,
    "risk_band" "risk_band",
    "last_heartbeat" TIMESTAMPTZ(6),
    "retention_anchor_at" TIMESTAMPTZ(6),
    "report_key" TEXT,
    "report_generated_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session_sections" (
    "session_id" UUID NOT NULL,
    "section_id" UUID NOT NULL,
    "position" INTEGER NOT NULL,
    "time_limit_ms" BIGINT,
    "started_at" TIMESTAMPTZ(6),
    "deadline_at" TIMESTAMPTZ(6),
    "ended_at" TIMESTAMPTZ(6),

    CONSTRAINT "session_sections_pkey" PRIMARY KEY ("session_id","section_id")
);

-- CreateTable
CREATE TABLE "session_questions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_id" UUID NOT NULL,
    "test_question_id" UUID NOT NULL,
    "question_version_id" UUID NOT NULL,
    "variant_id" UUID,
    "position" INTEGER NOT NULL,
    "points" DECIMAL(6,2) NOT NULL,
    "score" DECIMAL(6,2),
    "scoring" "question_scoring" NOT NULL DEFAULT 'AUTO',
    "scored_by" UUID,
    "scored_at" TIMESTAMPTZ(6),
    "scoring_note" TEXT,
    "final_code" TEXT,
    "final_language" TEXT,
    "answer" JSONB,

    CONSTRAINT "session_questions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "submissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_question_id" UUID NOT NULL,
    "kind" "submission_kind" NOT NULL,
    "language" TEXT NOT NULL,
    "source_code" TEXT NOT NULL,
    "results" JSONB NOT NULL DEFAULT '[]',
    "passed" INTEGER NOT NULL DEFAULT 0,
    "total" INTEGER NOT NULL DEFAULT 0,
    "score" DECIMAL(6,2),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "submissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "consent_texts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "version" TEXT NOT NULL,
    "body_md" TEXT NOT NULL,
    "legal_approved_at" TIMESTAMPTZ(6),
    "legal_approved_by" TEXT,
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "consent_texts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "consents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_id" UUID NOT NULL,
    "consent_text_id" UUID NOT NULL,
    "signed_name" TEXT,
    "signed_at" TIMESTAMPTZ(6),
    "declined_at" TIMESTAMPTZ(6),
    "ip" INET,
    "user_agent" TEXT,
    "pdf_key" TEXT,
    "pdf_generated_at" TIMESTAMPTZ(6),
    "copy_emailed_at" TIMESTAMPTZ(6),

    CONSTRAINT "consents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "identity_checks" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_id" UUID NOT NULL,
    "attempt" SMALLINT NOT NULL DEFAULT 1,
    "id_image_key" TEXT,
    "selfie_key" TEXT,
    "face_match_score" DECIMAL(5,4),
    "model_id" TEXT,
    "threshold" DECIMAL(5,4),
    "liveness_passed" BOOLEAN,
    "status" "identity_check_status" NOT NULL DEFAULT 'PENDING',
    "review_reason" "identity_review_reason",
    "manual_decision" "identity_manual_decision",
    "reviewed_by" UUID,
    "reviewed_at" TIMESTAMPTZ(6),
    "review_note" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "identity_checks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "media_chunks" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, -- DB-03 edit: Prisma emits BIGSERIAL
    "session_id" UUID NOT NULL,
    "stream" "media_stream" NOT NULL,
    "segment" INTEGER NOT NULL DEFAULT 0,
    "seq" INTEGER NOT NULL,
    "object_key" TEXT,
    "started_at" TIMESTAMPTZ(6) NOT NULL,
    "duration_ms" INTEGER NOT NULL,
    "size_bytes" BIGINT,
    "uploaded_at" TIMESTAMPTZ(6),
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "media_chunks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proctor_event_batches" (
    "session_id" UUID NOT NULL,
    "seq" INTEGER NOT NULL,
    "signature" BYTEA NOT NULL,
    "event_count" SMALLINT NOT NULL,
    "received_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "proctor_event_batches_pkey" PRIMARY KEY ("session_id","seq")
);

-- CreateTable
CREATE TABLE "proctor_events" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, -- DB-03 edit: Prisma emits BIGSERIAL
    "session_id" UUID NOT NULL,
    "batch_seq" INTEGER,
    "type" "event_type" NOT NULL,
    "severity" "severity" NOT NULL,
    "source" "event_source" NOT NULL DEFAULT 'CLIENT',
    "occurred_at" TIMESTAMPTZ(6) NOT NULL,
    "duration_ms" INTEGER,
    "confidence" DECIMAL(5,4),
    "payload" JSONB NOT NULL DEFAULT '{}',
    "evidence_key" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "proctor_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "keystroke_batches" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, -- DB-03 edit: Prisma emits BIGSERIAL
    "session_id" UUID NOT NULL,
    "session_question_id" UUID,
    "seq" INTEGER NOT NULL,
    "signature" BYTEA NOT NULL,
    "started_at" TIMESTAMPTZ(6) NOT NULL,
    "events" JSONB NOT NULL,

    CONSTRAINT "keystroke_batches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "session_reviews" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_id" UUID NOT NULL,
    "reviewer_id" UUID NOT NULL,
    "verdict" "verdict",
    "notes" TEXT,
    "started_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(6),

    CONSTRAINT "session_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "flag_decisions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "event_id" BIGINT NOT NULL,
    "reviewer_id" UUID NOT NULL,
    "decision" "flag_decision" NOT NULL,
    "note" TEXT,
    "decided_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "flag_decisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appeals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_review_id" UUID NOT NULL,
    "reason" TEXT NOT NULL,
    "status" "appeal_status" NOT NULL DEFAULT 'OPEN',
    "new_verdict" "verdict",
    "assigned_to" UUID,
    "resolution_note" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolved_at" TIMESTAMPTZ(6),

    CONSTRAINT "appeals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_endpoints" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "url" TEXT NOT NULL,
    "events" TEXT[] NOT NULL, -- DB-03 edit: NOT NULL, Prisma emits scalar lists as nullable
    "secret_enc" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by" UUID,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webhook_endpoints_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "webhook_deliveries" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, -- DB-03 edit: Prisma emits BIGSERIAL
    "endpoint_id" UUID NOT NULL,
    "event" TEXT NOT NULL,
    "session_id" UUID,
    "attempt" INTEGER NOT NULL,
    "status_code" INTEGER,
    "error" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "webhook_deliveries_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "users_set_password_token_hash_key" ON "users"("set_password_token_hash");

-- CreateIndex
CREATE INDEX "users_org_id_idx" ON "users"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "refresh_tokens_token_hash_key" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "refresh_tokens_user_id_idx" ON "refresh_tokens"("user_id");

-- CreateIndex
CREATE INDEX "refresh_tokens_family_id_idx" ON "refresh_tokens"("family_id");

-- CreateIndex
CREATE INDEX "audit_logs_org_id_created_at_idx" ON "audit_logs"("org_id", "created_at" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "questions_org_id_slug_key" ON "questions"("org_id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "question_versions_question_id_version_key" ON "question_versions"("question_id", "version");

-- CreateIndex
CREATE INDEX "test_cases_question_version_id_idx" ON "test_cases"("question_version_id");

-- CreateIndex
CREATE INDEX "question_variants_question_version_id_idx" ON "question_variants"("question_version_id");

-- CreateIndex
CREATE INDEX "variant_test_cases_test_case_id_idx" ON "variant_test_cases"("test_case_id");

-- CreateIndex
CREATE INDEX "ai_reference_solutions_question_version_id_idx" ON "ai_reference_solutions"("question_version_id");

-- CreateIndex
CREATE INDEX "tests_org_id_idx" ON "tests"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "tests_id_org_id_key" ON "tests"("id", "org_id");

-- CreateIndex
CREATE INDEX "test_sections_test_id_idx" ON "test_sections"("test_id");

-- CreateIndex
CREATE INDEX "test_questions_section_id_idx" ON "test_questions"("section_id");

-- CreateIndex
CREATE UNIQUE INDEX "candidates_org_id_email_key" ON "candidates"("org_id", "email");

-- CreateIndex
CREATE UNIQUE INDEX "candidates_id_org_id_key" ON "candidates"("id", "org_id");

-- CreateIndex
CREATE UNIQUE INDEX "invitations_token_hash_key" ON "invitations"("token_hash");

-- CreateIndex
CREATE INDEX "invitations_test_id_idx" ON "invitations"("test_id");

-- CreateIndex
CREATE INDEX "invitations_candidate_id_idx" ON "invitations"("candidate_id");

-- CreateIndex
CREATE UNIQUE INDEX "invitations_id_org_id_key" ON "invitations"("id", "org_id");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_invitation_id_key" ON "sessions"("invitation_id");

-- CreateIndex
CREATE INDEX "sessions_status_idx" ON "sessions"("status");

-- CreateIndex
CREATE INDEX "sessions_org_id_status_idx" ON "sessions"("org_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "session_sections_session_id_position_key" ON "session_sections"("session_id", "position");

-- CreateIndex
CREATE INDEX "session_questions_session_id_idx" ON "session_questions"("session_id");

-- CreateIndex
CREATE INDEX "submissions_session_question_id_created_at_idx" ON "submissions"("session_question_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "consent_texts_org_id_version_key" ON "consent_texts"("org_id", "version");

-- CreateIndex
CREATE UNIQUE INDEX "consents_session_id_key" ON "consents"("session_id");

-- CreateIndex
CREATE UNIQUE INDEX "identity_checks_session_id_attempt_key" ON "identity_checks"("session_id", "attempt");

-- CreateIndex
CREATE UNIQUE INDEX "media_chunks_session_id_stream_seq_key" ON "media_chunks"("session_id", "stream", "seq");

-- CreateIndex
CREATE INDEX "proctor_events_session_id_occurred_at_idx" ON "proctor_events"("session_id", "occurred_at");

-- CreateIndex
CREATE INDEX "proctor_events_session_id_severity_idx" ON "proctor_events"("session_id", "severity");

-- CreateIndex
CREATE UNIQUE INDEX "keystroke_batches_session_id_seq_key" ON "keystroke_batches"("session_id", "seq");

-- CreateIndex
CREATE UNIQUE INDEX "session_reviews_session_id_key" ON "session_reviews"("session_id");

-- CreateIndex
CREATE INDEX "session_reviews_reviewer_id_idx" ON "session_reviews"("reviewer_id");

-- CreateIndex
CREATE UNIQUE INDEX "flag_decisions_event_id_key" ON "flag_decisions"("event_id");

-- CreateIndex
CREATE UNIQUE INDEX "appeals_session_review_id_key" ON "appeals"("session_review_id");

-- CreateIndex
CREATE INDEX "appeals_assigned_to_idx" ON "appeals"("assigned_to");

-- CreateIndex
CREATE INDEX "webhook_deliveries_endpoint_id_created_at_idx" ON "webhook_deliveries"("endpoint_id", "created_at" DESC);

-- AddForeignKey
ALTER TABLE "organizations" ADD CONSTRAINT "fk_current_consent_text" FOREIGN KEY ("current_consent_text_id") REFERENCES "consent_texts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_replaced_by_fkey" FOREIGN KEY ("replaced_by") REFERENCES "refresh_tokens"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "questions" ADD CONSTRAINT "questions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "questions" ADD CONSTRAINT "questions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "questions" ADD CONSTRAINT "fk_current_version" FOREIGN KEY ("current_version_id") REFERENCES "question_versions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "question_versions" ADD CONSTRAINT "question_versions_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "test_cases" ADD CONSTRAINT "test_cases_question_version_id_fkey" FOREIGN KEY ("question_version_id") REFERENCES "question_versions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "question_variants" ADD CONSTRAINT "question_variants_question_version_id_fkey" FOREIGN KEY ("question_version_id") REFERENCES "question_versions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "variant_test_cases" ADD CONSTRAINT "variant_test_cases_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "question_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "variant_test_cases" ADD CONSTRAINT "variant_test_cases_test_case_id_fkey" FOREIGN KEY ("test_case_id") REFERENCES "test_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ai_reference_solutions" ADD CONSTRAINT "ai_reference_solutions_question_version_id_fkey" FOREIGN KEY ("question_version_id") REFERENCES "question_versions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ai_reference_solutions" ADD CONSTRAINT "ai_reference_solutions_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "question_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "ai_reference_solutions" ADD CONSTRAINT "ai_reference_solutions_collected_by_fkey" FOREIGN KEY ("collected_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tests" ADD CONSTRAINT "tests_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "tests" ADD CONSTRAINT "tests_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "test_sections" ADD CONSTRAINT "test_sections_test_id_fkey" FOREIGN KEY ("test_id") REFERENCES "tests"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "test_questions" ADD CONSTRAINT "test_questions_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "test_sections"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "test_questions" ADD CONSTRAINT "test_questions_question_version_id_fkey" FOREIGN KEY ("question_version_id") REFERENCES "question_versions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "candidates" ADD CONSTRAINT "candidates_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_test_id_org_id_fkey" FOREIGN KEY ("test_id", "org_id") REFERENCES "tests"("id", "org_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_candidate_id_org_id_fkey" FOREIGN KEY ("candidate_id", "org_id") REFERENCES "candidates"("id", "org_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_invitation_id_org_id_fkey" FOREIGN KEY ("invitation_id", "org_id") REFERENCES "invitations"("id", "org_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_sections" ADD CONSTRAINT "session_sections_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_sections" ADD CONSTRAINT "session_sections_section_id_fkey" FOREIGN KEY ("section_id") REFERENCES "test_sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_questions" ADD CONSTRAINT "session_questions_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_questions" ADD CONSTRAINT "session_questions_test_question_id_fkey" FOREIGN KEY ("test_question_id") REFERENCES "test_questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_questions" ADD CONSTRAINT "session_questions_question_version_id_fkey" FOREIGN KEY ("question_version_id") REFERENCES "question_versions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_questions" ADD CONSTRAINT "session_questions_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "question_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_questions" ADD CONSTRAINT "session_questions_scored_by_fkey" FOREIGN KEY ("scored_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "submissions" ADD CONSTRAINT "submissions_session_question_id_fkey" FOREIGN KEY ("session_question_id") REFERENCES "session_questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "consent_texts" ADD CONSTRAINT "consent_texts_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "consent_texts" ADD CONSTRAINT "consent_texts_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "consents" ADD CONSTRAINT "consents_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "consents" ADD CONSTRAINT "consents_consent_text_id_fkey" FOREIGN KEY ("consent_text_id") REFERENCES "consent_texts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "identity_checks" ADD CONSTRAINT "identity_checks_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "identity_checks" ADD CONSTRAINT "identity_checks_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "media_chunks" ADD CONSTRAINT "media_chunks_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proctor_event_batches" ADD CONSTRAINT "proctor_event_batches_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "proctor_events" ADD CONSTRAINT "proctor_events_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "keystroke_batches" ADD CONSTRAINT "keystroke_batches_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "keystroke_batches" ADD CONSTRAINT "keystroke_batches_session_question_id_fkey" FOREIGN KEY ("session_question_id") REFERENCES "session_questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_reviews" ADD CONSTRAINT "session_reviews_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "session_reviews" ADD CONSTRAINT "session_reviews_reviewer_id_fkey" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "flag_decisions" ADD CONSTRAINT "flag_decisions_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "proctor_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "flag_decisions" ADD CONSTRAINT "flag_decisions_reviewer_id_fkey" FOREIGN KEY ("reviewer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "appeals" ADD CONSTRAINT "appeals_session_review_id_fkey" FOREIGN KEY ("session_review_id") REFERENCES "session_reviews"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "appeals" ADD CONSTRAINT "appeals_assigned_to_fkey" FOREIGN KEY ("assigned_to") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "webhook_endpoints" ADD CONSTRAINT "webhook_endpoints_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "webhook_endpoints" ADD CONSTRAINT "webhook_endpoints_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_endpoint_id_fkey" FOREIGN KEY ("endpoint_id") REFERENCES "webhook_endpoints"("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION;

-- DB-03: CHECK constraints (ADR 0008 section 5). Explicit names, so tests can assert them (FU-DB-09).
-- The names are the ones Postgres would give an unnamed inline CHECK.
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_retention_days_check" CHECK ("retention_days" BETWEEN 7 AND 730);

ALTER TABLE "users" ADD CONSTRAINT "users_check" CHECK ("password_hash" IS NOT NULL OR "set_password_token_hash" IS NOT NULL);

ALTER TABLE "tests" ADD CONSTRAINT "tests_duration_minutes_check" CHECK ("duration_minutes" BETWEEN 5 AND 480);

ALTER TABLE "test_questions" ADD CONSTRAINT "test_questions_check" CHECK ("question_version_id" IS NOT NULL OR "random_rule" IS NOT NULL);

ALTER TABLE "invitations" ADD CONSTRAINT "invitations_check" CHECK ("window_end" > "window_start");

ALTER TABLE "sessions" ADD CONSTRAINT "sessions_risk_score_check" CHECK ("risk_score" BETWEEN 0 AND 100);

ALTER TABLE "session_questions" ADD CONSTRAINT "session_questions_check" CHECK (("scoring" = 'MANUAL') = ("scored_by" IS NOT NULL AND "scored_at" IS NOT NULL));

ALTER TABLE "consents" ADD CONSTRAINT "consents_check" CHECK (("signed_at" IS NULL) <> ("declined_at" IS NULL));

ALTER TABLE "consents" ADD CONSTRAINT "consents_check1" CHECK ("signed_at" IS NULL OR "signed_name" IS NOT NULL);

ALTER TABLE "identity_checks" ADD CONSTRAINT "identity_checks_attempt_check" CHECK ("attempt" BETWEEN 1 AND 2);

ALTER TABLE "identity_checks" ADD CONSTRAINT "identity_checks_check" CHECK (("status" = 'REVIEWED') = ("manual_decision" IS NOT NULL AND "reviewed_by" IS NOT NULL AND "reviewed_at" IS NOT NULL));

ALTER TABLE "appeals" ADD CONSTRAINT "appeals_check" CHECK (("status" = 'OVERTURNED') = ("new_verdict" IS NOT NULL));

-- DB-03: partial indexes (the other 22 indexes are above). NFR-05: the retention job reads the second one.
CREATE INDEX "sessions_risk_band_idx" ON "sessions"("risk_band") WHERE "status" IN ('GRADED', 'UNDER_REVIEW');

CREATE INDEX "sessions_retention_anchor_at_idx" ON "sessions"("retention_anchor_at") WHERE "retention_anchor_at" IS NOT NULL;

-- DB-03: users.updated_at is kept by the database, not by Prisma (the schema has no @updatedAt).
CREATE FUNCTION "set_updated_at"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW."updated_at" = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER "users_set_updated_at"
BEFORE UPDATE ON "users"
FOR EACH ROW
EXECUTE FUNCTION "set_updated_at"();
