/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/time': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Server clock, used to seed client countdown timers (FR-505) */
    get: operations['getServerTime'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The candidate's running session with the open section and its questions (FR-301, FR-505) */
    get: operations['getCandidateSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/questions/{questionId}/draft': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Autosave a code draft or an answer (FR-504) */
    put: operations['saveDraft'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/questions/{questionId}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run code against the sample tests (FR-502). One run per 5 seconds. */
    post: operations['runSampleTests'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/sections/{sectionId}/finish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Finish the open section. Final, it cannot be reopened (ADR 0002 S-1). */
    post: operations['finishSection'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Staff password login (FR-101). Placeholder path, see fsd.md section 4 (/auth/login). */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/enroll/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Begin forced TOTP enrollment (FR-102). Needs the challenge token from login. */
    post: operations['startTwoFactorEnrollment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/enroll/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm enrollment with a first code; returns the one-time recovery codes (ADR 0003 section 1) */
    post: operations['confirmTwoFactorEnrollment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/setup/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signed-in user begins optional TOTP set-up. Mirrors backend PR */
    post: operations['startTwoFactorSetup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/setup/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm optional set-up with a first code; returns the one-time recovery codes */
    post: operations['confirmTwoFactorSetup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Turn TOTP off. Needs password and TOTP code; revokes all refresh tokens and clears the cookie (backend PR */
    post: operations['disableTwoFactor'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/recovery-codes/regenerate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replace all recovery codes; the old set stops working */
    post: operations['regenerateRecoveryCodes'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete login with a 6-digit TOTP code or a recovery code (FR-102, ADR 0003 section 1) */
    post: operations['verifyTwoFactor'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the refresh cookie and return a new access token (FR-104). Cookie is httpOnly. */
    post: operations['refreshSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the refresh-token family and clear the cookie */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/password/forgot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a reset link. Always 202 with the same body (FR-107, D-22). */
    post: operations['forgotPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set a password with a single-use reset or invite token (FR-107, ADR 0003 section 4). Never signs in. */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Staff users of the caller's organisation (SUPER_ADMIN, FR-103) */
    get: operations['listStaffUsers'];
    put?: never;
    /** Invite a staff user by email; they set a password from the emailed link (ADR 0003 section 4) */
    post: operations['inviteStaffUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change a role or deactivate or reactivate a user (revokes their refresh tokens) */
    patch: operations['updateStaffUser'];
    trace?: never;
  };
  '/v1/admin/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Organisation settings (retention, erasure hold, risk scoring, decline contact) */
    get: operations['getOrgSettings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change some organisation settings */
    patch: operations['updateOrgSettings'];
    trace?: never;
  };
  '/v1/admin/consent-texts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consent document versions (D-17), newest first */
    get: operations['listConsentTexts'];
    put?: never;
    /** Add a new version. It starts as a placeholder; Legal approval is recorded outside this API (Q-43). */
    post: operations['createConsentText'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/consent-texts/{consentTextId}/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Make this version the one candidates sign */
    put: operations['setCurrentConsentText'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/candidates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Candidates of the organisation with their erasure state (list view only; the full page is FE-05) */
    get: operations['listCandidates'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/candidates/{candidateId}/erasure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request erasure of a candidate's data (NFR-05, D-19). Waits while a review or appeal is open if the hold is on. */
    post: operations['requestCandidateErasure'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** REAL. List questions (question:read). Readers without question:update see published versions only and never archived questions. */
    get: operations['listQuestions'];
    put?: never;
    /** REAL. Create a question with draft version 1 (question:create). */
    post: operations['createQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    /** REAL. One question with one version (the latest by default, `version` selects another). Callers with question:update get the full QuestionDetail. Every other reader (Recruiter) gets QuestionDetailRedacted: published versions only (a draft, a never-published, a missing and another organization's question are the identical 404), no revision, reference solution, answer key or validation report, and hidden test cases as id, position, isHidden and weight only. A published but archived question is still readable. */
    get: operations['getQuestion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** REAL. Change fields of the question (question:update). Every field is optional but at least one is needed. A draft is edited in place; if the latest version is published this creates the next version as a draft (createdNewVersion true). Test cases are NOT part of this body: use the test-case routes. expectedRevision (the revision as loaded) makes a concurrent change a 409. */
    patch: operations['updateQuestion'];
    trace?: never;
  };
  '/v1/questions/{questionId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** REAL. Publish the latest draft (question:update). 422 with errors[] while the draft is incomplete; for a CODING question also until a passing validation of the current revision exists (slice BE-04c), so coding questions cannot be published yet. 409 when there is no draft, the question is archived, or expectedRevision no longer matches. */
    post: operations['publishQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** REAL. Soft-archive a question (question:update); hidden from lists, never deleted. */
    post: operations['archiveQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/unarchive': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** REAL. Restore an archived question (question:update). */
    post: operations['unarchiveQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/versions/{version}/test-cases': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        version: number;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** REAL. Add a test case to a draft version of a coding question (question:update). */
    post: operations['addTestCase'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/versions/{version}/test-cases/{testCaseId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        version: number;
        testCaseId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** REAL. Remove a test case from a draft version (question:update). */
    delete: operations['removeTestCase'];
    options?: never;
    head?: never;
    /** REAL. Change a test case of a draft version (question:update). */
    patch: operations['updateTestCase'];
    trace?: never;
  };
  '/v1/questions/{questionId}/variants': {
    parameters: {
      query?: {
        version?: number;
      };
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    /** WEB-ONLY placeholder [BE-04b] (ADR 0007, explicit params per variant). Variants of a version, question:update only. */
    get: operations['getVariants'];
    /** WEB-ONLY placeholder [BE-04b]. Replace the variants of the latest draft version. */
    put: operations['putVariants'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/prefill': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** WEB-ONLY placeholder [BE-04b/c]. Run the reference solution on a variant's inputs and PROPOSE expected outputs (ADR 0007). Nothing is stored; the author must accept the proposals. */
    post: operations['prefillVariantOutputs'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/validate': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** WEB-ONLY placeholder [BE-04c] (permission question:validate). Start a validation job of the current content; the job binds to the revision it validated and stores it in the validation report. */
    post: operations['validateQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/validation/{jobId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        jobId: string;
      };
      cookie?: never;
    };
    /** WEB-ONLY placeholder [BE-04c]. Poll a validation job. */
    get: operations['getValidationJob'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/ai-references': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    /** WEB-ONLY placeholder [BE-04c] (ADR 0005, D-20). AI reference solutions of the question with the publish policy (Authors cannot read org settings). Similarity only, never grading. */
    get: operations['listAiReferences'];
    put?: never;
    /** WEB-ONLY placeholder [BE-04c]. Add a solution collected from an AI assistant (audited as ai_reference.create). */
    post: operations['addAiReference'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/ai-references/{referenceId}/supersede': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        referenceId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** WEB-ONLY placeholder [BE-04c]. Replace a row with a newer one; the old row keeps existing with supersededAt set (append-only, ADR 0005 AI-1). */
    post: operations['supersedeAiReference'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    StaffRole: 'SUPER_ADMIN' | 'RECRUITER' | 'AUTHOR' | 'REVIEWER';
    AuthUser: {
      id: string;
      email: string;
      name: string;
      role: components['schemas']['StaffRole'];
      orgName: string;
      totpEnabled: boolean;
    };
    AuthSession: {
      accessToken: string;
      user: components['schemas']['AuthUser'];
    };
    ChallengeRequest: {
      challengeToken: string;
    };
    LoginResult: {
      /** @enum {string} */
      status: 'authenticated' | 'two_factor_required' | 'two_factor_enrollment_required';
      session?: components['schemas']['AuthSession'];
      challengeToken?: string;
    };
    /** @enum {string} */
    QuestionType: 'CODING' | 'MCQ' | 'SHORT_ANSWER';
    /** @enum {string} */
    Difficulty: 'EASY' | 'MEDIUM' | 'HARD';
    Limits: {
      cpuMs: number;
      /** @description Not below cpuMs */
      wallMs: number;
      memoryKb: number;
    };
    /** @description A test slot. For a reader without question:update a HIDDEN case carries only id, position, isHidden and weight: the input and expectedOutput keys are absent, not null. */
    TestCase: {
      id: string;
      position: number;
      isHidden: boolean;
      weight: number;
      input?: string;
      expectedOutput?: string;
    };
    TestCaseInput: {
      input: string;
      expectedOutput: string;
      /** @default true */
      isHidden: boolean;
      /**
       * @description At most 2 decimals
       * @default 1
       */
      weight: number;
      /** @description Default after the last slot */
      position?: number;
    };
    TestCasePatch: {
      input?: string;
      expectedOutput?: string;
      isHidden?: boolean;
      weight?: number;
      position?: number;
    };
    McqOption: {
      id: string;
      text: string;
    };
    /** @description MCQ answer spec (the question type says which shape applies). 2 to 10 options. */
    McqAnswerSpec: {
      options: components['schemas']['McqOption'][];
      correctOptionIds: string[];
      multiple: boolean;
    };
    /** @description SHORT_ANSWER answer spec (D-23). */
    ShortAnswerSpec: {
      canonical: string;
      acceptedVariants: string[];
    };
    AnswerSpec: components['schemas']['McqAnswerSpec'] | components['schemas']['ShortAnswerSpec'];
    QuestionVersionRef: {
      id: string;
      version: number;
      isPublished: boolean;
      title: string;
      difficulty: components['schemas']['Difficulty'];
      /** Format: date-time */
      validatedAt: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    QuestionSummary: {
      id: string;
      slug: string;
      type: components['schemas']['QuestionType'];
      tags: string[];
      isArchived: boolean;
      /** Format: date-time */
      createdAt: string;
      /** @description The published version tests use; null until the first publish */
      published: components['schemas']['QuestionVersionRef'] | null;
      /** @description Highest version number (maybe a draft); for a reader without question:update the highest PUBLISHED version */
      latest: components['schemas']['QuestionVersionRef'];
    };
    QuestionList: {
      items: components['schemas']['QuestionSummary'][];
      page: number;
      pageSize: number;
      total: number;
    };
    /** @enum {string} */
    ValidationOutcome:
      'pass' | 'wrong_answer' | 'runtime_error' | 'compile_error' | 'limit_exceeded';
    ValidationResult: {
      /** @description Null for the base statement */
      variantId: string | null;
      variantLabel: string;
      testCaseId: string;
      position: number;
      language: components['schemas']['Language'];
      outcome: components['schemas']['ValidationOutcome'];
      message?: string;
    };
    /** @description Stored in the version's validationReport. The API defines `passed` and `revision` (the content revision the run validated; publish ignores a report of another revision). The other members are a WEB-ONLY placeholder [BE-04c]. */
    ValidationReport: {
      passed: boolean;
      revision: string;
      /** Format: date-time */
      finishedAt?: string;
      results?: components['schemas']['ValidationResult'][];
    } & {
      [key: string]: unknown;
    };
    ValidationJobRef: {
      jobId: string;
      /** @description The content revision the job validates */
      revision: string;
    };
    ValidationJob: {
      jobId: string;
      /** @description The content revision the job validated; a report for another revision must never be shown as current */
      revision: string;
      /** @enum {string} */
      status: 'queued' | 'running' | 'done' | 'failed';
      report?: components['schemas']['ValidationReport'];
      error?: string;
    };
    /** @description The full version a caller with question:update gets */
    QuestionVersion: components['schemas']['QuestionVersionRef'] & {
      statementMd: string;
      allowedLanguages: components['schemas']['Language'][];
      limits: components['schemas']['Limits'];
      starterCode: {
        [key: string]: string;
      };
      referenceSolution: {
        [key: string]: string;
      };
      answerSpec: components['schemas']['AnswerSpec'] | null;
      validationReport: components['schemas']['ValidationReport'] | null;
      /** @description Opaque SHA-256 of the version content and test cases (question:update only). Send it back as expectedRevision; it changes with every content or test-case change. */
      revision: string;
      testCases: components['schemas']['TestCase'][];
    };
    /** @description What a reader without question:update gets of a version: an allowlist. No revision, referenceSolution, answerSpec or validationReport, and hidden test cases without input and expectedOutput. */
    QuestionVersionRead: {
      id: string;
      version: number;
      isPublished: boolean;
      title: string;
      difficulty: components['schemas']['Difficulty'];
      /** Format: date-time */
      validatedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      statementMd: string;
      allowedLanguages: components['schemas']['Language'][];
      limits: components['schemas']['Limits'];
      starterCode: {
        [key: string]: string;
      };
      testCases: components['schemas']['TestCase'][];
    };
    /** @description A question with one full version (question:update) */
    QuestionDetail: components['schemas']['QuestionSummary'] & {
      /** @description Oldest first */
      versions: components['schemas']['QuestionVersionRef'][];
      version: components['schemas']['QuestionVersion'];
      /** @description true when this PATCH created a new version because the latest was published */
      createdNewVersion: boolean;
    };
    /** @description The detail a reader without question:update gets (an allowlist, DL-32, BE-04a staff-view.ts) */
    QuestionDetailRedacted: {
      id: string;
      slug: string;
      type: components['schemas']['QuestionType'];
      tags: string[];
      isArchived: boolean;
      /** Format: date-time */
      createdAt: string;
      published: components['schemas']['QuestionVersionRef'] | null;
      latest: components['schemas']['QuestionVersionRef'];
      versions: components['schemas']['QuestionVersionRef'][];
      version: components['schemas']['QuestionVersionRead'];
      createdNewVersion: boolean;
    };
    CreateQuestion: {
      type?: components['schemas']['QuestionType'];
      /** @description Unique per organization; generated from the title when omitted */
      slug?: string;
      title: string;
      statementMd: string;
      difficulty: components['schemas']['Difficulty'];
      tags?: string[];
      allowedLanguages?: components['schemas']['Language'][];
      limits?: components['schemas']['Limits'];
      starterCode?: {
        [key: string]: string;
      };
      referenceSolution?: {
        [key: string]: string;
      };
      answerSpec?: components['schemas']['AnswerSpec'];
      testCases?: components['schemas']['TestCaseInput'][];
    };
    /** @description Every field is optional, at least one is needed. Test cases have their own routes. */
    UpdateQuestion: {
      expectedRevision?: string;
      title?: string;
      statementMd?: string;
      difficulty?: components['schemas']['Difficulty'];
      tags?: string[];
      allowedLanguages?: components['schemas']['Language'][];
      limits?: components['schemas']['Limits'];
      starterCode?: {
        [key: string]: string;
      };
      referenceSolution?: {
        [key: string]: string;
      };
      answerSpec?: components['schemas']['AnswerSpec'];
    };
    PublishRequest: {
      expectedRevision?: string;
    };
    /** @description RFC 7807 problem body of the question routes. 409 and 422 carry detail and errors[] only: no machine code, the caller tells cases apart by endpoint and status. */
    Problem: {
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      traceId?: string;
      errors?: string[];
    };
    VariantOverride: {
      testCaseId: string;
      input: string;
      expectedOutput: string;
    };
    /** @description WEB-ONLY placeholder [BE-04b]. Explicit params per variant (ADR 0007), no parameter schema. */
    Variant: {
      id: string;
      label: string;
      params: {
        [key: string]: string | number;
      };
      active: boolean;
      overrides: components['schemas']['VariantOverride'][];
    };
    VariantList: {
      variants: components['schemas']['Variant'][];
    };
    /** @description Org settings aiReferences.* (ADR 0005 AI-4, AI-5), read-only here because Authors cannot read org settings */
    AiReferencePolicy: {
      refreshDays: number;
      minAssistants: number;
    };
    AiReferenceInput: {
      assistant: string;
      modelLabel: string;
      language: components['schemas']['Language'];
      solutionCode: string;
      promptText?: string;
      /** Format: date-time */
      collectedAt: string;
      /** @description Null means the base statement */
      variantId?: string | null;
    };
    AiReference: components['schemas']['AiReferenceInput'] & {
      id: string;
      collectedByName: string;
      /** Format: date-time */
      supersededAt: string | null;
    };
    AiReferenceList: {
      items: components['schemas']['AiReference'][];
      policy: components['schemas']['AiReferencePolicy'];
    };
    PrefillRequest: {
      language: components['schemas']['Language'];
      params: {
        [key: string]: unknown;
      };
      /** @description The template as edited (may be unsaved); the API renders it with params */
      referenceSolution: string;
      slots: {
        testCaseId: string;
        /** @description The input that applies to this variant */
        input: string;
      }[];
    };
    PrefillResponse: {
      proposals: {
        testCaseId: string;
        expectedOutput?: string;
        /** @description Why no output could be produced (runtime error */
        error?: string;
      }[];
    };
    ApiError: {
      code: string;
      message: string;
    };
    ProblemDetails: {
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance: string;
      traceId: string;
      errors?: string[];
      /** @enum {string} */
      code?: 'REAUTH_FAILED' | 'TWO_FACTOR_REQUIRED_FOR_ROLE';
    };
    RecoveryCodes: {
      recoveryCodes: string[];
    };
    /** @enum {string} */
    Language: 'python' | 'javascript' | 'java';
    DraftRequest: {
      /** @enum {string} */
      kind: 'code' | 'mcq';
      language?: components['schemas']['Language'];
      code?: string;
      selectedOptionId?: string | null;
    };
    RunRequest: {
      language: components['schemas']['Language'];
      code: string;
    };
    SampleTestResult: {
      id: string;
      name: string;
      /** @enum {string} */
      status: 'passed' | 'failed';
      input?: string;
      expectedOutput?: string;
      actualOutput?: string;
      durationMs?: number;
    };
    RunResult: {
      /** @enum {string} */
      outcome: 'completed' | 'compile_error' | 'runtime_error' | 'time_limit_exceeded';
      tests: components['schemas']['SampleTestResult'][];
      stdout: string;
      stderr: string;
    };
    SampleTest: {
      id: string;
      name: string;
      input: string;
      expectedOutput: string;
    };
    Question: {
      id: string;
      /** @enum {string} */
      type: 'coding' | 'mcq';
      title: string;
      points: number;
      statementMarkdown: string;
      languages?: components['schemas']['Language'][];
      /** @description Starter code keyed by language */
      starterCode?: {
        [key: string]: string;
      };
      sampleTests?: components['schemas']['SampleTest'][];
      options?: {
        id: string;
        label: string;
      }[];
    };
    CandidateSession: {
      testTitle: string;
      /** Format: date-time */
      testDeadlineAt: string;
      section: {
        id: string;
        position: number;
        totalSections: number;
        title: string;
        /** Format: date-time */
        deadlineAt: string | null;
      };
      /** @description Questions of the open section only */
      questions: components['schemas']['Question'][];
    };
    StaffUser: {
      id: string;
      email: string;
      name: string;
      role: components['schemas']['StaffRole'];
      /** @enum {string} */
      status: 'invited' | 'active' | 'deactivated';
      /** Format: date-time */
      lastLoginAt?: string | null;
    };
    /** @enum {string} */
    EventSeverity: 'LOW' | 'MEDIUM' | 'HIGH';
    /** @description FR-804 and ADR 0005 section 2. Weights are keyed by event type. */
    RiskSettings: {
      severityPoints: {
        LOW: number;
        MEDIUM: number;
        HIGH: number;
      };
      capPerType: number;
      bandMinScore: {
        MEDIUM: number;
        HIGH: number;
      };
      weights: {
        [key: string]: number;
      };
    };
    OrgSettings: {
      retentionDays: number;
      erasure: {
        holdWhileReviewOrAppealOpen: boolean;
      };
      risk: components['schemas']['RiskSettings'];
      consentDeclineContact: string;
    };
    OrgSettingsPatch: {
      retentionDays?: number;
      erasure?: {
        holdWhileReviewOrAppealOpen?: boolean;
      };
      risk?: components['schemas']['RiskSettings'];
      consentDeclineContact?: string;
    };
    ConsentText: {
      id: string;
      version: string;
      bodyMd: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      legalApprovedAt: string | null;
      legalApprovedBy?: string | null;
      isCurrent: boolean;
    };
    CandidateSummary: {
      id: string;
      name: string;
      email: string;
      /** Format: date-time */
      lastSessionAt?: string | null;
      erasure: {
        /**
         * @description waiting = held while a review or appeal is open (D-19)
         * @enum {string}
         */
        state: 'none' | 'waiting' | 'queued' | 'erased';
        /** Format: date-time */
        requestedAt?: string | null;
        /** @enum {string|null} */
        waitingFor?: 'review' | 'appeal' | null;
      };
    };
  };
  responses: {
    /** @description The role is not allowed to call this route (FR-103) */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiError'];
      };
    };
  };
  parameters: {
    QuestionId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API is up */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok';
          };
        };
      };
    };
  };
  getServerTime: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current server time */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            serverNow: string;
          };
        };
      };
    };
  };
  getCandidateSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateSession'];
        };
      };
    };
  };
  saveDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: components['parameters']['QuestionId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DraftRequest'];
      };
    };
    responses: {
      /** @description Draft stored */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            savedAt: string;
          };
        };
      };
    };
  };
  runSampleTests: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: components['parameters']['QuestionId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RunRequest'];
      };
    };
    responses: {
      /** @description Sample test results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunResult'];
        };
      };
      /** @description Too many runs */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            retryAfterSeconds: number;
          };
        };
      };
    };
  };
  finishSection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sectionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Section closed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            finishedAt: string;
            nextSectionId?: string | null;
          };
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Signed in, or a second step is needed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResult'];
        };
      };
      /** @description Sign-in failed. One generic answer for a wrong password, an unknown email and a locked account (15 minutes after 5 failed attempts, FR-101); the API never reveals which. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  startTwoFactorEnrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChallengeRequest'];
      };
    };
    responses: {
      /** @description Secret and otpauth URI for the QR code */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            manualKey: string;
            otpauthUri: string;
          };
        };
      };
      /** @description Challenge expired, sign in again */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  confirmTwoFactorEnrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          challengeToken: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Enrolled and signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            session: components['schemas']['AuthSession'];
            recoveryCodes: string[];
          };
        };
      };
      /** @description Wrong code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Challenge expired, sign in again */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  startTwoFactorSetup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
        };
      };
    };
    responses: {
      /** @description Secret, otpauth URI and QR code (PNG data URL) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            manualKey: string;
            otpauthUri: string;
            qrDataUrl: string;
          };
        };
      };
      /** @description Missing or invalid currentPassword or totpCode */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Wrong current password or locked account, one identical body with code REAUTH_FAILED. Never a session expiry (that is 401). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor was turned on concurrently */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  confirmTwoFactorSetup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Two-factor is on */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecoveryCodes'];
        };
      };
      /** @description Wrong code, or missing or invalid body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Wrong current password or locked account, one identical body with code REAUTH_FAILED. Never a session expiry (that is 401). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor state changed concurrently */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  disableTwoFactor: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
          /** @description 6-digit TOTP code only; a recovery code is 400 */
          totpCode: string;
        };
      };
    };
    responses: {
      /** @description Two-factor is off and every refresh token of the user is revoked (sign in again) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid currentPassword or totpCode */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description REAUTH_FAILED for a wrong or locked password or a wrong or replayed code (one identical body), otherwise TWO_FACTOR_REQUIRED_FOR_ROLE for Super Admin and Reviewer (checked last) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor is not on */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Temporary outage (for example the code store); no failure is counted, try again */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  regenerateRecoveryCodes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
        };
      };
    };
    responses: {
      /** @description The new codes, shown once */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecoveryCodes'];
        };
      };
      /** @description Missing or invalid currentPassword or totpCode */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Wrong current password or locked account, one identical body with code REAUTH_FAILED. Never a session expiry (that is 401). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor is not on */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  verifyTwoFactor: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          challengeToken: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      /** @description Wrong code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Challenge expired, sign in again */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description New access token */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      /** @description No valid refresh cookie */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
        };
      };
    };
    responses: {
      /** @description Accepted, whether or not the account exists */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          token: string;
          newPassword: string;
        };
      };
    };
    responses: {
      /** @description Password set, token consumed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token invalid, expired or already used (one message for all three) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listStaffUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['StaffUser'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  inviteStaffUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          name: string;
          role: components['schemas']['StaffRole'];
        };
      };
    };
    responses: {
      /** @description Invited */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StaffUser'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description A user with this email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  updateStaffUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          role?: components['schemas']['StaffRole'];
          active?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StaffUser'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such user in this organisation */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Refused, for example deactivating yourself or the last Super Admin */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  getOrgSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Settings, with defaults for missing keys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrgSettings'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  updateOrgSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OrgSettingsPatch'];
      };
    };
    responses: {
      /** @description Updated settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrgSettings'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  listConsentTexts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versions and whether this environment refuses unapproved texts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description REQUIRE_LEGAL_APPROVED_CONSENT (true in pilot and production) */
            legalApprovalRequired: boolean;
            items: components['schemas']['ConsentText'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  createConsentText: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          version: string;
          bodyMd: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentText'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description This version name already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  setCurrentConsentText: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consentTextId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Now current */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentText'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Refused because the text is not approved by Legal and approval is required */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listCandidates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Candidates */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['CandidateSummary'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  requestCandidateErasure: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        candidateId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted; the body says whether it waits */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateSummary'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such candidate in this organisation */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listQuestions: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
        tag?: string;
        difficulty?: components['schemas']['Difficulty'];
        type?: components['schemas']['QuestionType'];
        includeArchived?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description One page of questions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionList'];
        };
      };
      /** @description Invalid filter, or a page that is too deep */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  createQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateQuestion'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      /** @description Validation failed (errors[] lists each problem) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description The slug is taken in this organization */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  getQuestion: {
    parameters: {
      query?: {
        version?: number;
      };
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Question */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['QuestionDetail']
            | components['schemas']['QuestionDetailRedacted'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such question or version for this caller */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  updateQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateQuestion'];
      };
    };
    responses: {
      /** @description Saved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      /** @description Validation failed, or no field sent */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such question in your organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description The question is archived, or it changed since it was loaded (expectedRevision); detail only, no code */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  publishQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PublishRequest'];
      };
    };
    responses: {
      /** @description Published */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such question in your organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description No draft to publish, the question is archived, or expectedRevision no longer matches */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description The draft is incomplete or not validated; errors[] says what */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  archiveQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archived */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionSummary'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such question in your organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  unarchiveQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Restored */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionSummary'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such question in your organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  addTestCase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        version: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TestCaseInput'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TestCase'];
        };
      };
      /** @description Validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such question or version in your organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description The version is published (immutable), or the question is archived */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description Not a coding question, or too many test cases */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  removeTestCase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        version: number;
        testCaseId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components['responses']['Forbidden'];
      /** @description No such question, version or test case in your organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description The version is published (immutable), or the question is archived */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  updateTestCase: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        version: number;
        testCaseId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TestCasePatch'];
      };
    };
    responses: {
      /** @description Changed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TestCase'];
        };
      };
      /** @description Validation failed, or no field sent */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such question, version or test case in your organization */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description The version is published (immutable), or the question is archived */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  getVariants: {
    parameters: {
      query?: {
        version?: number;
      };
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Variants */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VariantList'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  putVariants: {
    parameters: {
      query?: {
        version?: number;
      };
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VariantList'];
      };
    };
    responses: {
      /** @description Saved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VariantList'];
        };
      };
      /** @description Invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** @description The version is published (immutable), or the question is archived */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  prefillVariantOutputs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PrefillRequest'];
      };
    };
    responses: {
      /** @description One proposal per slot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PrefillResponse'];
        };
      };
      /** @description Invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  validateQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Job accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationJobRef'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  getValidationJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Job state; the report is present when done */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationJob'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  listAiReferences: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rows (including superseded ones) and the policy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AiReferenceList'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  addAiReference: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AiReferenceInput'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AiReference'];
        };
      };
      /** @description Invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
  supersedeAiReference: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        referenceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AiReferenceInput'];
      };
    };
    responses: {
      /** @description The new row */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AiReference'];
        };
      };
      /** @description Invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
    };
  };
}
