/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/time': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Server clock, used to seed client countdown timers (FR-505) */
    get: operations['getServerTime'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The candidate's running session with the open section and its questions (FR-301, FR-505) */
    get: operations['getCandidateSession'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/questions/{questionId}/draft': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Autosave a code draft or an answer (FR-504) */
    put: operations['saveDraft'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/questions/{questionId}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run code against the sample tests (FR-502). One run per 5 seconds. */
    post: operations['runSampleTests'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/candidate/sections/{sectionId}/finish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Finish the open section. Final, it cannot be reopened (ADR 0002 S-1). */
    post: operations['finishSection'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Staff password login (FR-101). Placeholder path, see fsd.md section 4 (/auth/login). */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/enroll/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Begin forced TOTP enrollment (FR-102). Needs the challenge token from login. */
    post: operations['startTwoFactorEnrollment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/enroll/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm enrollment with a first code; returns the one-time recovery codes (ADR 0003 section 1) */
    post: operations['confirmTwoFactorEnrollment'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/setup/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Signed-in user begins optional TOTP set-up. Mirrors backend PR */
    post: operations['startTwoFactorSetup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/setup/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm optional set-up with a first code; returns the one-time recovery codes */
    post: operations['confirmTwoFactorSetup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Turn TOTP off. Needs password and TOTP code; revokes all refresh tokens and clears the cookie (backend PR */
    post: operations['disableTwoFactor'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/recovery-codes/regenerate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replace all recovery codes; the old set stops working */
    post: operations['regenerateRecoveryCodes'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/2fa/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Complete login with a 6-digit TOTP code or a recovery code (FR-102, ADR 0003 section 1) */
    post: operations['verifyTwoFactor'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the refresh cookie and return a new access token (FR-104). Cookie is httpOnly. */
    post: operations['refreshSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the refresh-token family and clear the cookie */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/password/forgot': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a reset link. Always 202 with the same body (FR-107, D-22). */
    post: operations['forgotPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/password/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set a password with a single-use reset or invite token (FR-107, ADR 0003 section 4). Never signs in. */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Staff users of the caller's organisation (SUPER_ADMIN, FR-103) */
    get: operations['listStaffUsers'];
    put?: never;
    /** Invite a staff user by email; they set a password from the emailed link (ADR 0003 section 4) */
    post: operations['inviteStaffUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change a role or deactivate or reactivate a user (revokes their refresh tokens) */
    patch: operations['updateStaffUser'];
    trace?: never;
  };
  '/v1/admin/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Organisation settings (retention, erasure hold, risk scoring, decline contact) */
    get: operations['getOrgSettings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change some organisation settings */
    patch: operations['updateOrgSettings'];
    trace?: never;
  };
  '/v1/admin/consent-texts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consent document versions (D-17), newest first */
    get: operations['listConsentTexts'];
    put?: never;
    /** Add a new version. It starts as a placeholder; Legal approval is recorded outside this API (Q-43). */
    post: operations['createConsentText'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/consent-texts/{consentTextId}/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Make this version the one candidates sign */
    put: operations['setCurrentConsentText'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/candidates': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Candidates of the organisation with their erasure state (list view only; the full page is FE-05) */
    get: operations['listCandidates'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/admin/candidates/{candidateId}/erasure': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request erasure of a candidate's data (NFR-05, D-19). Waits while a review or appeal is open if the hold is on. */
    post: operations['requestCandidateErasure'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Questions of the organisation (list view). Needs question:read. */
    get: operations['listQuestions'];
    put?: never;
    /** Create a question as draft version 1 (TC-010). Needs question:create. */
    post: operations['createQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    /** The current version with its tests, variants, reference solutions and answer key. Author only, never sent to candidates (TC-011). */
    get: operations['getQuestion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Save the content. A published version is immutable, so this creates the next draft version (FR-204). */
    patch: operations['updateQuestion'];
    trace?: never;
  };
  '/v1/questions/{questionId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    /** Version history (FR-204) */
    get: operations['listQuestionVersions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/versions/{version}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        version: number;
      };
      cookie?: never;
    };
    /** One version, read-only (published versions never change) */
    get: operations['getQuestionVersion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/validate': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a validation job of the saved version (reference solution on every slot of every active variant, ADR 0007 V-3) */
    post: operations['validateQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/validation/{jobId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        jobId: string;
      };
      cookie?: never;
    };
    /** Poll a validation job */
    get: operations['getValidationJob'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish the current draft version. Refused (409) without a passing validation of the saved content (TC-012) or without the AI reference solutions of the publish gate (ADR 0005 AI-5). */
    post: operations['publishQuestion'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/ai-references': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    /** AI reference solutions of the current version, including superseded rows (D-20). Similarity only, never grading. */
    get: operations['listAiReferences'];
    put?: never;
    /** Add a solution collected from an AI assistant (audited as ai_reference.create) */
    post: operations['addAiReference'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/questions/{questionId}/ai-references/{referenceId}/supersede': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        referenceId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replace a row with a newer one; the old row keeps existing with supersededAt set (append-only, ADR 0005 AI-1) */
    post: operations['supersedeAiReference'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    StaffRole: 'SUPER_ADMIN' | 'RECRUITER' | 'AUTHOR' | 'REVIEWER';
    AuthUser: {
      id: string;
      email: string;
      name: string;
      role: components['schemas']['StaffRole'];
      orgName: string;
      totpEnabled: boolean;
    };
    AuthSession: {
      accessToken: string;
      user: components['schemas']['AuthUser'];
    };
    ChallengeRequest: {
      challengeToken: string;
    };
    LoginResult: {
      /** @enum {string} */
      status: 'authenticated' | 'two_factor_required' | 'two_factor_enrollment_required';
      session?: components['schemas']['AuthSession'];
      challengeToken?: string;
    };
    /** @enum {string} */
    QuestionType: 'CODING' | 'MCQ' | 'SHORT_ANSWER';
    /** @enum {string} */
    Difficulty: 'EASY' | 'MEDIUM' | 'HARD';
    /** @enum {string} */
    QuestionStatus: 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';
    QuestionSummary: {
      id: string;
      slug: string;
      title: string;
      type: components['schemas']['QuestionType'];
      difficulty: components['schemas']['Difficulty'];
      tags: string[];
      status: components['schemas']['QuestionStatus'];
      /** @description Latest version number */
      version: number;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    ParamType: 'string' | 'number' | 'boolean' | 'array';
    ParamDef: {
      name: string;
      type: components['schemas']['ParamType'];
    };
    Limits: {
      cpuMs: number;
      wallMs: number;
      memoryKb: number;
    };
    TestCase: {
      /** @description Client-generated for new rows */
      id: string;
      input: string;
      expectedOutput: string;
      isHidden: boolean;
      weight: number;
    };
    VariantOverride: {
      testCaseId: string;
      input: string;
      expectedOutput: string;
    };
    Variant: {
      id: string;
      label: string;
      params: {
        [key: string]: unknown;
      };
      active: boolean;
      overrides: components['schemas']['VariantOverride'][];
    };
    McqOption: {
      id: string;
      text: string;
    };
    McqAnswerSpec: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'McqAnswerSpec';
      options: components['schemas']['McqOption'][];
      correctOptionIds: string[];
      multiple: boolean;
    };
    ShortAnswerSpec: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'ShortAnswerSpec';
      canonical: string;
      acceptedVariants: string[];
    };
    AnswerSpec: components['schemas']['McqAnswerSpec'] | components['schemas']['ShortAnswerSpec'];
    QuestionContent: {
      title: string;
      /** @description Markdown */
      statementMd: string;
      difficulty: components['schemas']['Difficulty'];
      tags: string[];
      allowedLanguages: components['schemas']['Language'][];
      limits: components['schemas']['Limits'];
      starterCode: {
        [key: string]: string;
      };
      referenceSolution: {
        [key: string]: string;
      };
      paramSchema: components['schemas']['ParamDef'][];
      testCases: components['schemas']['TestCase'][];
      variants: components['schemas']['Variant'][];
      answerSpec: Omit<components['schemas']['AnswerSpec'], 'type'> | null;
    };
    QuestionCreate: components['schemas']['QuestionContent'] & {
      type: components['schemas']['QuestionType'];
    };
    /** @enum {string} */
    ValidationOutcome:
      'pass' | 'wrong_answer' | 'runtime_error' | 'compile_error' | 'limit_exceeded';
    ValidationResult: {
      /** @description Null for the base statement */
      variantId: string | null;
      variantLabel: string;
      testCaseId: string;
      position: number;
      language: components['schemas']['Language'];
      outcome: components['schemas']['ValidationOutcome'];
      message?: string;
    };
    ValidationReport: {
      passed: boolean;
      /** Format: date-time */
      finishedAt: string;
      results: components['schemas']['ValidationResult'][];
    };
    ValidationJobRef: {
      jobId: string;
    };
    ValidationJob: {
      jobId: string;
      /** @enum {string} */
      status: 'queued' | 'running' | 'done' | 'failed';
      report?: components['schemas']['ValidationReport'];
      error?: string;
    };
    /** @description Org settings aiReferences.* (ADR 0005 AI-4, AI-5), read-only here because Authors cannot read org settings */
    AiReferencePolicy: {
      refreshDays: number;
      minAssistants: number;
    };
    QuestionVersion: components['schemas']['QuestionContent'] & {
      version: number;
      isPublished: boolean;
      /** Format: date-time */
      createdAt: string;
      /**
       * Format: date-time
       * @description Cleared by any save
       */
      validatedAt: string | null;
      validationReport: components['schemas']['ValidationReport'];
    };
    QuestionDetail: {
      id: string;
      slug: string;
      type: components['schemas']['QuestionType'];
      status: components['schemas']['QuestionStatus'];
      latestVersion: number;
      aiReferencePolicy: components['schemas']['AiReferencePolicy'];
      current: components['schemas']['QuestionVersion'];
    };
    QuestionVersionSummary: {
      version: number;
      isPublished: boolean;
      /** Format: date-time */
      createdAt: string;
      createdByName: string;
      /** Format: date-time */
      validatedAt: string | null;
    };
    AiReferenceInput: {
      assistant: string;
      modelLabel: string;
      language: components['schemas']['Language'];
      solutionCode: string;
      promptText?: string;
      /** Format: date-time */
      collectedAt: string;
      /** @description Null means the base statement */
      variantId?: string | null;
    };
    AiReference: components['schemas']['AiReferenceInput'] & {
      id: string;
      collectedByName: string;
      /** Format: date-time */
      supersededAt: string | null;
    };
    ApiError: {
      code: string;
      message: string;
    };
    ProblemDetails: {
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance: string;
      traceId: string;
      errors?: string[];
      /** @enum {string} */
      code?: 'REAUTH_FAILED' | 'TWO_FACTOR_REQUIRED_FOR_ROLE';
    };
    RecoveryCodes: {
      recoveryCodes: string[];
    };
    /** @enum {string} */
    Language: 'python' | 'javascript' | 'java';
    DraftRequest: {
      /** @enum {string} */
      kind: 'code' | 'mcq';
      language?: components['schemas']['Language'];
      code?: string;
      selectedOptionId?: string | null;
    };
    RunRequest: {
      language: components['schemas']['Language'];
      code: string;
    };
    SampleTestResult: {
      id: string;
      name: string;
      /** @enum {string} */
      status: 'passed' | 'failed';
      input?: string;
      expectedOutput?: string;
      actualOutput?: string;
      durationMs?: number;
    };
    RunResult: {
      /** @enum {string} */
      outcome: 'completed' | 'compile_error' | 'runtime_error' | 'time_limit_exceeded';
      tests: components['schemas']['SampleTestResult'][];
      stdout: string;
      stderr: string;
    };
    SampleTest: {
      id: string;
      name: string;
      input: string;
      expectedOutput: string;
    };
    Question: {
      id: string;
      /** @enum {string} */
      type: 'coding' | 'mcq';
      title: string;
      points: number;
      statementMarkdown: string;
      languages?: components['schemas']['Language'][];
      /** @description Starter code keyed by language */
      starterCode?: {
        [key: string]: string;
      };
      sampleTests?: components['schemas']['SampleTest'][];
      options?: {
        id: string;
        label: string;
      }[];
    };
    CandidateSession: {
      testTitle: string;
      /** Format: date-time */
      testDeadlineAt: string;
      section: {
        id: string;
        position: number;
        totalSections: number;
        title: string;
        /** Format: date-time */
        deadlineAt: string | null;
      };
      /** @description Questions of the open section only */
      questions: components['schemas']['Question'][];
    };
    StaffUser: {
      id: string;
      email: string;
      name: string;
      role: components['schemas']['StaffRole'];
      /** @enum {string} */
      status: 'invited' | 'active' | 'deactivated';
      /** Format: date-time */
      lastLoginAt?: string | null;
    };
    /** @enum {string} */
    EventSeverity: 'LOW' | 'MEDIUM' | 'HIGH';
    /** @description FR-804 and ADR 0005 section 2. Weights are keyed by event type. */
    RiskSettings: {
      severityPoints: {
        LOW: number;
        MEDIUM: number;
        HIGH: number;
      };
      capPerType: number;
      bandMinScore: {
        MEDIUM: number;
        HIGH: number;
      };
      weights: {
        [key: string]: number;
      };
    };
    OrgSettings: {
      retentionDays: number;
      erasure: {
        holdWhileReviewOrAppealOpen: boolean;
      };
      risk: components['schemas']['RiskSettings'];
      consentDeclineContact: string;
    };
    OrgSettingsPatch: {
      retentionDays?: number;
      erasure?: {
        holdWhileReviewOrAppealOpen?: boolean;
      };
      risk?: components['schemas']['RiskSettings'];
      consentDeclineContact?: string;
    };
    ConsentText: {
      id: string;
      version: string;
      bodyMd: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      legalApprovedAt: string | null;
      legalApprovedBy?: string | null;
      isCurrent: boolean;
    };
    CandidateSummary: {
      id: string;
      name: string;
      email: string;
      /** Format: date-time */
      lastSessionAt?: string | null;
      erasure: {
        /**
         * @description waiting = held while a review or appeal is open (D-19)
         * @enum {string}
         */
        state: 'none' | 'waiting' | 'queued' | 'erased';
        /** Format: date-time */
        requestedAt?: string | null;
        /** @enum {string|null} */
        waitingFor?: 'review' | 'appeal' | null;
      };
    };
  };
  responses: {
    /** @description The role is not allowed to call this route (FR-103) */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ApiError'];
      };
    };
  };
  parameters: {
    QuestionId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API is up */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'ok';
          };
        };
      };
    };
  };
  getServerTime: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current server time */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            serverNow: string;
          };
        };
      };
    };
  };
  getCandidateSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session snapshot */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateSession'];
        };
      };
    };
  };
  saveDraft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: components['parameters']['QuestionId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DraftRequest'];
      };
    };
    responses: {
      /** @description Draft stored */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            savedAt: string;
          };
        };
      };
    };
  };
  runSampleTests: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: components['parameters']['QuestionId'];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RunRequest'];
      };
    };
    responses: {
      /** @description Sample test results */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunResult'];
        };
      };
      /** @description Too many runs */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            retryAfterSeconds: number;
          };
        };
      };
    };
  };
  finishSection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        sectionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Section closed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** Format: date-time */
            finishedAt: string;
            nextSectionId?: string | null;
          };
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          password: string;
        };
      };
    };
    responses: {
      /** @description Signed in, or a second step is needed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResult'];
        };
      };
      /** @description Sign-in failed. One generic answer for a wrong password, an unknown email and a locked account (15 minutes after 5 failed attempts, FR-101); the API never reveals which. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  startTwoFactorEnrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChallengeRequest'];
      };
    };
    responses: {
      /** @description Secret and otpauth URI for the QR code */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            manualKey: string;
            otpauthUri: string;
          };
        };
      };
      /** @description Challenge expired, sign in again */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  confirmTwoFactorEnrollment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          challengeToken: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Enrolled and signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            session: components['schemas']['AuthSession'];
            recoveryCodes: string[];
          };
        };
      };
      /** @description Wrong code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Challenge expired, sign in again */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  startTwoFactorSetup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
        };
      };
    };
    responses: {
      /** @description Secret, otpauth URI and QR code (PNG data URL) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            manualKey: string;
            otpauthUri: string;
            qrDataUrl: string;
          };
        };
      };
      /** @description Missing or invalid currentPassword or totpCode */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Wrong current password or locked account, one identical body with code REAUTH_FAILED. Never a session expiry (that is 401). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor was turned on concurrently */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  confirmTwoFactorSetup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Two-factor is on */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecoveryCodes'];
        };
      };
      /** @description Wrong code, or missing or invalid body */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Wrong current password or locked account, one identical body with code REAUTH_FAILED. Never a session expiry (that is 401). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor state changed concurrently */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  disableTwoFactor: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
          /** @description 6-digit TOTP code only; a recovery code is 400 */
          totpCode: string;
        };
      };
    };
    responses: {
      /** @description Two-factor is off and every refresh token of the user is revoked (sign in again) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid currentPassword or totpCode */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description REAUTH_FAILED for a wrong or locked password or a wrong or replayed code (one identical body), otherwise TWO_FACTOR_REQUIRED_FOR_ROLE for Super Admin and Reviewer (checked last) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor is not on */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Temporary outage (for example the code store); no failure is counted, try again */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  regenerateRecoveryCodes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          currentPassword: string;
        };
      };
    };
    responses: {
      /** @description The new codes, shown once */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecoveryCodes'];
        };
      };
      /** @description Missing or invalid currentPassword or totpCode */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Missing or invalid access token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Wrong current password or locked account, one identical body with code REAUTH_FAILED. Never a session expiry (that is 401). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
      /** @description Two-factor is not on */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProblemDetails'];
        };
      };
    };
  };
  verifyTwoFactor: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          challengeToken: string;
          code: string;
        };
      };
    };
    responses: {
      /** @description Signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      /** @description Wrong code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Challenge expired, sign in again */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description New access token */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthSession'];
        };
      };
      /** @description No valid refresh cookie */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed out */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
        };
      };
    };
    responses: {
      /** @description Accepted, whether or not the account exists */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            message: string;
          };
        };
      };
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          token: string;
          newPassword: string;
        };
      };
    };
    responses: {
      /** @description Password set, token consumed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Token invalid, expired or already used (one message for all three) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listStaffUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Users */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['StaffUser'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  inviteStaffUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          email: string;
          name: string;
          role: components['schemas']['StaffRole'];
        };
      };
    };
    responses: {
      /** @description Invited */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StaffUser'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description A user with this email already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  updateStaffUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          role?: components['schemas']['StaffRole'];
          active?: boolean;
        };
      };
    };
    responses: {
      /** @description Updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StaffUser'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such user in this organisation */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description Refused, for example deactivating yourself or the last Super Admin */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  getOrgSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Settings, with defaults for missing keys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrgSettings'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  updateOrgSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OrgSettingsPatch'];
      };
    };
    responses: {
      /** @description Updated settings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrgSettings'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  listConsentTexts: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versions and whether this environment refuses unapproved texts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @description REQUIRE_LEGAL_APPROVED_CONSENT (true in pilot and production) */
            legalApprovalRequired: boolean;
            items: components['schemas']['ConsentText'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  createConsentText: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          version: string;
          bodyMd: string;
        };
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentText'];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description This version name already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  setCurrentConsentText: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        consentTextId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Now current */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentText'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Refused because the text is not approved by Legal and approval is required */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listCandidates: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Candidates */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['CandidateSummary'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  requestCandidateErasure: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        candidateId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted; the body says whether it waits */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CandidateSummary'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description No such candidate in this organisation */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listQuestions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Questions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['QuestionSummary'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  createQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuestionCreate'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      /** @description Invalid content */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  getQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Question */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  updateQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['QuestionContent'];
      };
    };
    responses: {
      /** @description Saved; the returned version is the one that was edited or created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      /** @description Invalid content */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listQuestionVersions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Versions, newest first */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['QuestionVersionSummary'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  getQuestionVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        version: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  validateQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Job accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationJobRef'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  getValidationJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Job state; the report is present when done */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationJob'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  publishQuestion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Published */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuestionDetail'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      /** @description validation_required, or ai_references_missing */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  listAiReferences: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rows */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: components['schemas']['AiReference'][];
          };
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  addAiReference: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AiReferenceInput'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AiReference'];
        };
      };
      /** @description Invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
  supersedeAiReference: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        questionId: string;
        referenceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AiReferenceInput'];
      };
    };
    responses: {
      /** @description The new row */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AiReference'];
        };
      };
      /** @description Invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiError'];
        };
      };
    };
  };
}
