import type { CodeLanguage } from '@codeproctor/shared';

/** FR-501: completion is limited to language keywords. No identifiers, snippets or AI. */
export const LANGUAGE_KEYWORDS: Record<CodeLanguage, readonly string[]> = {
  python: [
    'and',
    'as',
    'break',
    'class',
    'continue',
    'def',
    'elif',
    'else',
    'except',
    'False',
    'finally',
    'for',
    'from',
    'if',
    'import',
    'in',
    'is',
    'lambda',
    'None',
    'not',
    'or',
    'pass',
    'raise',
    'return',
    'True',
    'try',
    'while',
    'with',
    'yield',
  ],
  javascript: [
    'break',
    'case',
    'catch',
    'class',
    'const',
    'continue',
    'default',
    'else',
    'export',
    'false',
    'finally',
    'for',
    'function',
    'if',
    'import',
    'let',
    'new',
    'null',
    'return',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'typeof',
    'var',
    'while',
    'of',
    'in',
  ],
  java: [
    'abstract',
    'boolean',
    'break',
    'case',
    'catch',
    'char',
    'class',
    'continue',
    'default',
    'double',
    'else',
    'extends',
    'false',
    'final',
    'finally',
    'for',
    'if',
    'implements',
    'import',
    'int',
    'interface',
    'long',
    'new',
    'null',
    'private',
    'protected',
    'public',
    'return',
    'static',
    'switch',
    'this',
    'throw',
    'true',
    'try',
    'void',
    'while',
  ],
};

export const LANGUAGE_LABELS: Record<CodeLanguage, string> = {
  python: 'Python',
  javascript: 'JavaScript',
  java: 'Java',
};
