-- consent_age_confirmed_at: the candidate's 18-or-older confirmation (owner decision C-30, D-55; ADR 0008
-- post-freeze delta). Forward-only and additive. The column is NULL on a decline and on every row that
-- exists before this migration, so there is no backfill.
-- Generated by `prisma migrate diff`, not edited.
--
-- Deliberately NO CHECK constraint. A CHECK (signed_at IS NULL OR age_confirmed_at IS NOT NULL), even
-- NOT VALID, is evaluated on every later UPDATE of the row. It would therefore block the consent-PDF
-- job's update of pdf_key, pdf_generated_at and copy_emailed_at on a row signed before C-30. The
-- requirement is enforced at create instead: ConsentService requires `ageConfirmed: true` and sets the
-- timestamp (server time) under the ADR 0013 CS-4.4 create grant.
--
-- No GRANT is needed: app_user holds its privileges on consents at table level (audit_append_only), and
-- a table-level privilege covers a column added later.

-- AlterTable
ALTER TABLE "consents" ADD COLUMN     "age_confirmed_at" TIMESTAMPTZ(6);
