-- identity_check_waiver_columns: the video-check columns of identity_checks, their foreign key, and
-- the two CHECK constraints of a WAIVED row (ADR 0015 section 4; ADR 0008 post-freeze change).
-- Forward-only and additive. Existing rows get NULL in the three new columns and are not WAIVED, so
-- both CHECK constraints hold for them and no backfill is needed.
-- Generated by `prisma migrate diff`, then edited by hand: the two CHECK constraints at the end
-- (marked "ADR 0015 edit:") are SQL that Prisma cannot express. Nothing else differs from what
-- Prisma generated.
-- Needs the previous migration (identity_check_waived_enum): the first CHECK constraint names WAIVED.

-- AlterTable
ALTER TABLE "identity_checks" ADD COLUMN     "video_check_at" TIMESTAMPTZ(6),
ADD COLUMN     "video_check_by" UUID,
ADD COLUMN     "video_check_done" BOOLEAN;

-- AddForeignKey
-- NO ACTION, as reviewed_by. Not org-composite: the service guarantees the user is in the same org.
ALTER TABLE "identity_checks" ADD CONSTRAINT "identity_checks_video_check_by_fkey" FOREIGN KEY ("video_check_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ADR 0015 edit: a WAIVED row is the first attempt and carries no identity data: no images, no match
-- result, no manual review. The existing identity_checks_check already allows WAIVED (a WAIVED row is
-- not REVIEWED and has a NULL manual_decision), so it is unchanged.
ALTER TABLE "identity_checks" ADD CONSTRAINT "identity_checks_waived_check" CHECK ("status" <> 'WAIVED' OR ("attempt" = 1 AND "id_image_key" IS NULL AND "selfie_key" IS NULL AND "face_match_score" IS NULL AND "model_id" IS NULL AND "threshold" IS NULL AND "liveness_passed" IS NULL AND "review_reason" IS NULL AND "manual_decision" IS NULL AND "reviewed_by" IS NULL AND "reviewed_at" IS NULL AND "review_note" IS NULL));

-- ADR 0015 edit: the video check is all or nothing, and only a WAIVED row can carry one.
ALTER TABLE "identity_checks" ADD CONSTRAINT "identity_checks_video_check_check" CHECK (("video_check_done" IS NULL) = ("video_check_by" IS NULL) AND ("video_check_done" IS NULL) = ("video_check_at" IS NULL) AND ("video_check_done" IS NULL OR "status" = 'WAIVED'));
