-- identity_check_waived_enum: the WAIVED value of identity_check_status, appended last (ADR 0015
-- section 4; ADR 0008 post-freeze change). It is not a rejection, so ADR 0004 section 1 stands.
-- Only the ALTER TYPE is here, in its own migration: Postgres refuses to use a new enum value in the
-- transaction that adds it, and the next migration's CHECK constraint names WAIVED.
-- Generated by `prisma migrate diff`; nothing was edited.

-- AlterEnum
ALTER TYPE "identity_check_status" ADD VALUE 'WAIVED';
