// Delivery rows of the seed (DB-04): 5 candidates, 7 invitations with their sessions, and for the
// three sessions that finished the test: signed consents, identity checks, sections, served
// questions, submissions, proctor events with their batches, a risk score each, and one completed
// review with flag decisions. A pure function of `now` and the content plan.
//
// Reading of the prompt (recorded in the PR): "5 candidates in different states (INVITED, CONSENTED,
// EXPIRED, DECLINED, COMPLETED)" and "3 completed sessions, a risk score in each band, one completed
// review" are met by 7 sessions. ADR 0002 section 2 lets a MEDIUM or HIGH session reach COMPLETED
// only through a verdict, and the prompt allows one completed review, so of the three finished
// sessions one is LOW and COMPLETED, one is MEDIUM and COMPLETED with the review, and one is HIGH and
// UNDER_REVIEW (waiting for a reviewer).
import type { Prisma } from '../../apps/api/src/generated/prisma/client';
import { type ContentPlan, TEST_KEYS } from './content';
import { ID, syntheticSignature, unusableTokenHash } from './ids';
import { mcqQuestion, shortAnswerQuestion } from './non-coding';
import { codingQuestions } from './questions';
import { SEEDED_EVENT_SEVERITY, type SeededEventType, riskBand, riskScore } from './risk';
import type { Language } from './types';
import { renderSources, resolveSlots } from './variants';

const MIN = 60_000;
const HOUR = 60 * MIN;
const DAY = 24 * HOUR;

export interface PlannedEvent {
  /**
   * Stable lookup key: session id, type, and the event's rank among the events of that type in the
   * session by time. It does not depend on the run time, so a second run finds the events a first
   * run stored (the id is generated by the database).
   */
  readonly key: string;
  readonly row: Omit<Prisma.ProctorEventCreateManyInput, 'id'>;
}

export interface PlannedFlagDecision {
  readonly eventKey: string;
  readonly row: Omit<Prisma.FlagDecisionCreateManyInput, 'eventId'>;
}

export interface DeliveryPlan {
  readonly candidates: Prisma.CandidateCreateManyInput[];
  readonly invitations: Prisma.InvitationCreateManyInput[];
  readonly sessions: Prisma.SessionCreateManyInput[];
  readonly sessionSections: Prisma.SessionSectionCreateManyInput[];
  readonly sessionQuestions: Prisma.SessionQuestionCreateManyInput[];
  readonly submissions: Prisma.SubmissionCreateManyInput[];
  readonly consents: Prisma.ConsentCreateManyInput[];
  readonly identityChecks: Prisma.IdentityCheckCreateManyInput[];
  readonly proctorEventBatches: Prisma.ProctorEventBatchCreateManyInput[];
  readonly proctorEvents: PlannedEvent[];
  readonly sessionReviews: Prisma.SessionReviewCreateManyInput[];
  readonly flagDecisions: PlannedFlagDecision[];
  readonly auditLogs: Prisma.AuditLogCreateManyInput[];
}

type MutableDeliveryPlan = { -readonly [K in keyof DeliveryPlan]: DeliveryPlan[K] };

const CANDIDATES = [
  { key: 'avery', email: 'avery.stone@candidates.example', fullName: 'Avery Stone', ref: 1001 },
  { key: 'bao', email: 'bao.tran@candidates.example', fullName: 'Bao Tran', ref: 1002 },
  { key: 'carmen', email: 'carmen.ruiz@candidates.example', fullName: 'Carmen Ruiz', ref: 1003 },
  { key: 'dev', email: 'dev.okonkwo@candidates.example', fullName: 'Dev Okonkwo', ref: 1004 },
  { key: 'elif', email: 'elif.yilmaz@candidates.example', fullName: 'Elif Yilmaz', ref: 1005 },
] as const;
type CandidateKey = (typeof CANDIDATES)[number]['key'];

type TestKey = 'backend' | 'senior';
const TEST_ID_KEY: Record<TestKey, string> = {
  backend: TEST_KEYS.backend,
  senior: TEST_KEYS.senior,
};
const DURATION_MIN: Record<TestKey, number> = { backend: 60, senior: 90 };
// Sections run in order and never reopen (ADR 0002 S-1). Offsets are minutes after started_at.
const SECTION_LIMIT_MIN: Record<TestKey, readonly (number | null)[]> = {
  backend: [20, null],
  senior: [15, 45, null],
};
const SECTION_SPANS_MIN: Record<TestKey, readonly (readonly [number, number])[]> = {
  backend: [
    [0, 17],
    [17, 52],
  ],
  senior: [
    [0, 12],
    [12, 50],
    [50, 78],
  ],
};
const SUBMITTED_AFTER_MIN: Record<TestKey, number> = { backend: 52, senior: 78 };

type Outcome =
  | { kind: 'SOLVED'; language: Language }
  | { kind: 'NOT_ATTEMPTED' }
  | { kind: 'MCQ'; selected: string }
  | { kind: 'SHORT_AUTO'; text: string }
  | { kind: 'SHORT_MANUAL'; text: string; note: string };

interface ServedScript {
  readonly slug: string;
  readonly sectionPosition: number;
  /** Position of the test_questions row inside its section. */
  readonly testQuestionPosition: number;
  readonly variantIndex: number | null;
  readonly outcome: Outcome;
}

interface EventScript {
  readonly type: SeededEventType;
  /** Minutes after started_at. */
  readonly atMin: number;
  /** Client batch seq, or null for an event the server writes. */
  readonly batch: number | null;
  readonly durationMs?: number;
  readonly confidence?: string;
  readonly payload?: (ctx: EventContext) => Prisma.InputJsonObject;
  readonly flag?: { decision: 'CONFIRMED' | 'DISMISSED'; note: string };
}

interface EventContext {
  readonly at: Date;
  /** The session_questions id at a position inside this session. */
  readonly sessionQuestionId: (position: number) => string;
}

interface FinishedScript {
  readonly served: readonly ServedScript[];
  readonly events: readonly EventScript[];
  readonly review?: {
    readonly verdict: 'CLEAN' | 'SUSPICIOUS' | 'VIOLATION';
    readonly notes: string;
  };
}

interface SessionScript {
  readonly key: string;
  readonly candidate: CandidateKey;
  readonly test: TestKey;
  readonly status: 'INVITED' | 'CONSENTED' | 'EXPIRED' | 'DECLINED' | 'COMPLETED' | 'UNDER_REVIEW';
  readonly sentAgoMs: number;
  /** Finished sessions only: how long before `now` the test started. */
  readonly startedAgoMs?: number;
  readonly finished?: FinishedScript;
}

const solved = (language: Language): Outcome => ({ kind: 'SOLVED', language });
const NOT_ATTEMPTED: Outcome = { kind: 'NOT_ATTEMPTED' };

const SA_SYNTHETIC_NOTE = 'Synthetic seed data.';

// LOW session (Elif, backend screen). Score: FOCUS_LOST 8 + 2 x PASTE_ATTEMPT 4 + RIGHT_CLICK 2 = 14.
const ELIF: FinishedScript = {
  served: [
    {
      slug: 'parcel-surcharge',
      sectionPosition: 1,
      testQuestionPosition: 1,
      variantIndex: 2,
      outcome: solved('python'),
    },
    {
      slug: 'sensor-bursts',
      sectionPosition: 1,
      testQuestionPosition: 2,
      variantIndex: 1,
      outcome: solved('javascript'),
    },
    {
      slug: mcqQuestion.slug,
      sectionPosition: 1,
      testQuestionPosition: 3,
      variantIndex: null,
      outcome: { kind: 'MCQ', selected: 'a' },
    },
    {
      slug: shortAnswerQuestion.slug,
      sectionPosition: 1,
      testQuestionPosition: 4,
      variantIndex: null,
      outcome: { kind: 'SHORT_AUTO', text: 'HTTP 403 FORBIDDEN' },
    },
    {
      slug: 'steady-stretch',
      sectionPosition: 2,
      testQuestionPosition: 1,
      variantIndex: 0,
      outcome: solved('java'),
    },
    {
      slug: 'stock-rebalance',
      sectionPosition: 2,
      testQuestionPosition: 2,
      variantIndex: 2,
      outcome: NOT_ATTEMPTED,
    },
  ],
  events: [
    { type: 'FOCUS_LOST', atMin: 9, batch: 1, durationMs: 4200 },
    { type: 'PASTE_ATTEMPT', atMin: 10, batch: 1, payload: () => ({ length: 120 }) },
    {
      type: 'DISCONNECTED',
      atMin: 21,
      batch: null,
      payload: (ctx) => ({ lastHeartbeatAt: new Date(ctx.at.getTime() - 15_000).toISOString() }),
    },
    { type: 'RECONNECTED', atMin: 22, batch: null },
    { type: 'PASTE_ATTEMPT', atMin: 27, batch: 2, payload: () => ({ length: 45 }) },
    { type: 'RIGHT_CLICK', atMin: 33, batch: 2 },
  ],
};

// MEDIUM session (Carmen, backend screen, first attempt). Score: 2 x FULLSCREEN_EXIT 16 +
// TAB_SWITCH 8 + GAZE_AWAY 8 + COPY_ATTEMPT 2 + 2 x PASTE_ATTEMPT 4 = 38. Completed review.
const CARMEN: FinishedScript = {
  served: [
    {
      slug: 'parcel-surcharge',
      sectionPosition: 1,
      testQuestionPosition: 1,
      variantIndex: 1,
      outcome: solved('python'),
    },
    {
      slug: 'sensor-bursts',
      sectionPosition: 1,
      testQuestionPosition: 2,
      variantIndex: 2,
      outcome: solved('python'),
    },
    {
      slug: mcqQuestion.slug,
      sectionPosition: 1,
      testQuestionPosition: 3,
      variantIndex: null,
      outcome: { kind: 'MCQ', selected: 'c' },
    },
    {
      slug: shortAnswerQuestion.slug,
      sectionPosition: 1,
      testQuestionPosition: 4,
      variantIndex: null,
      outcome: {
        kind: 'SHORT_MANUAL',
        text: 'The 403 status: the server knows who you are and refuses anyway',
        note: `Same meaning as 403 Forbidden. ${SA_SYNTHETIC_NOTE}`,
      },
    },
    {
      slug: 'steady-stretch',
      sectionPosition: 2,
      testQuestionPosition: 1,
      variantIndex: 1,
      outcome: solved('python'),
    },
    {
      slug: 'stock-rebalance',
      sectionPosition: 2,
      testQuestionPosition: 2,
      variantIndex: 0,
      outcome: NOT_ATTEMPTED,
    },
  ],
  events: [
    {
      type: 'FULLSCREEN_EXIT',
      atMin: 8,
      batch: 1,
      durationMs: 8000,
      flag: { decision: 'CONFIRMED', note: 'Left fullscreen for 8 seconds. Synthetic seed data.' },
    },
    { type: 'FULLSCREEN_RESTORED', atMin: 8.2, batch: 1 },
    {
      type: 'TAB_SWITCH',
      atMin: 20,
      batch: 2,
      flag: { decision: 'CONFIRMED', note: 'Switched tabs once. Synthetic seed data.' },
    },
    {
      type: 'GAZE_AWAY',
      atMin: 24,
      batch: 2,
      durationMs: 6000,
      confidence: '0.8200',
      flag: {
        decision: 'DISMISSED',
        note: 'Brief glance away, no other person or device visible. Synthetic seed data.',
      },
    },
    { type: 'COPY_ATTEMPT', atMin: 25, batch: 2, payload: () => ({ length: 30 }) },
    {
      type: 'FULLSCREEN_EXIT',
      atMin: 36,
      batch: 3,
      durationMs: 12000,
      flag: { decision: 'CONFIRMED', note: 'Second fullscreen exit. Synthetic seed data.' },
    },
    { type: 'FULLSCREEN_RESTORED', atMin: 36.3, batch: 3 },
    { type: 'PASTE_ATTEMPT', atMin: 40, batch: 3, payload: () => ({ length: 200 }) },
    { type: 'PASTE_ATTEMPT', atMin: 44, batch: 3, payload: () => ({ length: 64 }) },
  ],
  review: {
    verdict: 'SUSPICIOUS',
    notes:
      'Two fullscreen exits and a tab switch, no other evidence. Verdict SUSPICIOUS, no further action. Synthetic seed data.',
  },
};

// HIGH session (Avery, senior screen), waiting for a reviewer. Score: 2 x TAB_SWITCH 16 +
// SCREEN_SHARE_STOPPED 20 + PASTE_BURST 20 + CODE_SIMILARITY 20 = 76.
// Position 4 is the HARD question; the burst and the similarity refer to it.
const AVERY: FinishedScript = {
  served: [
    {
      slug: 'sensor-bursts',
      sectionPosition: 1,
      testQuestionPosition: 1,
      variantIndex: 0,
      outcome: solved('python'),
    },
    {
      slug: 'steady-stretch',
      sectionPosition: 2,
      testQuestionPosition: 1,
      variantIndex: 0,
      outcome: solved('python'),
    },
    {
      slug: 'maintenance-windows',
      sectionPosition: 2,
      testQuestionPosition: 1,
      variantIndex: 2,
      outcome: solved('python'),
    },
    {
      slug: 'toll-vouchers',
      sectionPosition: 3,
      testQuestionPosition: 1,
      variantIndex: 1,
      outcome: solved('python'),
    },
  ],
  events: [
    { type: 'TAB_SWITCH', atMin: 14, batch: 1 },
    { type: 'TAB_SWITCH', atMin: 30, batch: 1 },
    {
      type: 'SCREEN_SHARE_STOPPED',
      atMin: 52,
      batch: 2,
      payload: () => ({ reason: 'TRACK_ENDED' }),
    },
    { type: 'SCREEN_SHARE_RESUMED', atMin: 53, batch: 2 },
    {
      type: 'PASTE_BURST',
      atMin: 58,
      batch: null,
      payload: (ctx) => ({
        sessionQuestionId: ctx.sessionQuestionId(4),
        insertedChars: 1450,
        windowMs: 900,
      }),
    },
    {
      type: 'CODE_SIMILARITY',
      atMin: 76,
      batch: null,
      confidence: '0.9400',
      payload: (ctx) => ({
        sessionQuestionId: ctx.sessionQuestionId(4),
        similarity: 0.94,
        aiReferenceSolutionId: ID.aiReference('toll-vouchers', 'assistantA', 'python'),
      }),
    },
  ],
};

const SESSIONS: readonly SessionScript[] = [
  {
    key: 'avery-backend',
    candidate: 'avery',
    test: 'backend',
    status: 'INVITED',
    sentAgoMs: 2 * HOUR,
  },
  {
    key: 'bao-backend',
    candidate: 'bao',
    test: 'backend',
    status: 'CONSENTED',
    sentAgoMs: 2 * DAY,
  },
  {
    key: 'carmen-backend-1',
    candidate: 'carmen',
    test: 'backend',
    status: 'COMPLETED',
    sentAgoMs: 20 * DAY,
    startedAgoMs: 18 * DAY,
    finished: CARMEN,
  },
  {
    key: 'carmen-backend-2',
    candidate: 'carmen',
    test: 'backend',
    status: 'EXPIRED',
    sentAgoMs: 12 * DAY,
  },
  { key: 'dev-backend', candidate: 'dev', test: 'backend', status: 'DECLINED', sentAgoMs: 3 * DAY },
  {
    key: 'elif-backend',
    candidate: 'elif',
    test: 'backend',
    status: 'COMPLETED',
    sentAgoMs: 9 * DAY,
    startedAgoMs: 8 * DAY,
    finished: ELIF,
  },
  {
    key: 'avery-senior',
    candidate: 'avery',
    test: 'senior',
    status: 'UNDER_REVIEW',
    sentAgoMs: 5 * DAY,
    startedAgoMs: 4 * DAY,
    finished: AVERY,
  },
];

const CODE_COMMENT: Record<Language, string> = { python: '#', javascript: '//', java: '//' };
const WINDOW_DAYS = 7;
const USER_AGENT = 'Mozilla/5.0 (synthetic seed data) Chromium/130';

/** The seed writes every points value as a string such as "15.00". */
export function eventKey(sessionId: string, type: string, rank: number): string {
  return `${sessionId}|${type}|${rank}`;
}

function pointsString(value: unknown): string {
  if (typeof value !== 'string') throw new Error('The seed writes points as strings.');
  return value;
}

export function buildDelivery(now: Date, content: ContentPlan): DeliveryPlan {
  const at = (ms: number): Date => new Date(ms);
  const reviewer = ID.user('reviewer');
  const recruiter = ID.user('recruiter');

  const plan: MutableDeliveryPlan = {
    candidates: CANDIDATES.map((c) => ({
      id: ID.candidate(c.key),
      orgId: ID.org,
      email: c.email,
      fullName: c.fullName,
      externalRef: `demo-ats-${c.ref}`,
    })),
    invitations: [],
    sessions: [],
    sessionSections: [],
    sessionQuestions: [],
    submissions: [],
    consents: [],
    identityChecks: [],
    proctorEventBatches: [],
    proctorEvents: [],
    sessionReviews: [],
    flagDecisions: [],
    auditLogs: [],
  };

  const pointsOf = new Map<string, string>(
    content.testQuestions.map((row) => [row.id as string, pointsString(row.points)]),
  );
  const sectionRows = new Map(content.testSections.map((row) => [row.id as string, row]));
  const codingBySlug = new Map(codingQuestions.map((spec) => [spec.slug, spec]));

  for (const script of SESSIONS) {
    const candidate = CANDIDATES.find((c) => c.key === script.candidate);
    if (candidate === undefined) throw new Error(`Unknown candidate ${script.candidate}.`);
    const invitationId = ID.invitation(script.key);
    const sessionId = ID.session(script.key);
    const testId = ID.test(TEST_ID_KEY[script.test]);
    const sentAt = now.getTime() - script.sentAgoMs;
    const windowStart = sentAt;
    const windowEnd = sentAt + WINDOW_DAYS * DAY;
    const startedAt =
      script.startedAgoMs === undefined ? undefined : now.getTime() - script.startedAgoMs;

    plan.invitations.push({
      id: invitationId,
      orgId: ID.org,
      testId,
      candidateId: ID.candidate(script.candidate),
      tokenHash: unusableTokenHash(`invitation:${script.key}`),
      windowStart: at(windowStart),
      windowEnd: at(windowEnd),
      sentAt: at(sentAt),
      usedAt: startedAt === undefined ? null : at(startedAt),
      createdById: recruiter,
      createdAt: at(sentAt - MIN),
    });

    const base = {
      id: sessionId,
      orgId: ID.org,
      invitationId,
      createdAt: at(sentAt - MIN),
    } as const;

    switch (script.status) {
      case 'INVITED':
        plan.sessions.push({ ...base, status: 'INVITED' });
        break;
      case 'CONSENTED': {
        const signedAt = at(now.getTime() - 3 * HOUR);
        plan.sessions.push({ ...base, status: 'CONSENTED', authEpoch: 1 });
        plan.consents.push({
          id: ID.consent(script.key),
          sessionId,
          consentTextId: ID.consentText,
          signedName: candidate.fullName,
          signedAt,
          ip: '203.0.113.20',
          userAgent: USER_AGENT,
        });
        break;
      }
      case 'EXPIRED':
        plan.sessions.push({
          ...base,
          status: 'EXPIRED',
          retentionAnchorAt: at(windowEnd + 3 * MIN),
        });
        break;
      case 'DECLINED': {
        const declinedAt = at(sentAt + 20 * MIN);
        plan.sessions.push({
          ...base,
          status: 'DECLINED',
          authEpoch: 1,
          retentionAnchorAt: declinedAt,
        });
        plan.consents.push({
          id: ID.consent(script.key),
          sessionId,
          consentTextId: ID.consentText,
          declinedAt,
          ip: '203.0.113.21',
          userAgent: USER_AGENT,
        });
        break;
      }
      case 'COMPLETED':
      case 'UNDER_REVIEW': {
        const finished = script.finished;
        if (finished === undefined || startedAt === undefined) {
          throw new Error(`${script.key} needs a finished script and a start time.`);
        }
        addFinishedSession(plan, {
          script,
          finished,
          candidateName: candidate.fullName,
          candidateIndex: CANDIDATES.indexOf(candidate),
          base,
          startedAt,
          content,
          pointsOf,
          sectionRows,
          codingBySlug,
          reviewer,
        });
        break;
      }
    }
  }

  // Audit log (append-only): a few staff actions. IDs and action names only (ADR 0001 C-3).
  const carmenSession = ID.session('carmen-backend-1');
  const carmenReview = plan.sessionReviews.find((row) => row.sessionId === carmenSession);
  const manualQuestion = plan.sessionQuestions.find(
    (row) => row.sessionId === carmenSession && row.scoring === 'MANUAL',
  );
  const staffAction = (
    actorId: string,
    action: string,
    entityType: string,
    entityId: string,
    createdAt: Date,
    ip: string,
    metadata: Prisma.InputJsonObject = {},
  ): Prisma.AuditLogCreateManyInput => ({
    orgId: ID.org,
    actorId,
    action,
    entityType,
    entityId,
    ip,
    metadata,
    createdAt,
  });
  plan.auditLogs.push(
    staffAction(
      ID.user('super-admin'),
      'consent_text.create',
      'consent_text',
      ID.consentText,
      at(now.getTime() - 30 * DAY),
      '203.0.113.10',
    ),
    staffAction(
      recruiter,
      'test.create',
      'test',
      ID.test(TEST_KEYS.backend),
      at(now.getTime() - 29 * DAY),
      '203.0.113.11',
    ),
    staffAction(
      recruiter,
      'test.create',
      'test',
      ID.test(TEST_KEYS.senior),
      at(now.getTime() - 29 * DAY + HOUR),
      '203.0.113.11',
    ),
  );
  if (manualQuestion?.scoredAt !== undefined && manualQuestion.id !== undefined) {
    plan.auditLogs.push(
      staffAction(
        reviewer,
        'scoring.manual',
        'session_question',
        manualQuestion.id,
        manualQuestion.scoredAt as Date,
        '203.0.113.12',
        { sessionId: carmenSession },
      ),
    );
  }
  if (carmenReview?.completedAt !== undefined && carmenReview.id !== undefined) {
    plan.auditLogs.push(
      staffAction(
        reviewer,
        'review.complete',
        'session_review',
        carmenReview.id,
        carmenReview.completedAt as Date,
        '203.0.113.12',
        { sessionId: carmenSession },
      ),
    );
  }

  return plan;
}

interface FinishedContext {
  readonly script: SessionScript;
  readonly finished: FinishedScript;
  readonly candidateName: string;
  readonly candidateIndex: number;
  readonly base: {
    readonly id: string;
    readonly orgId: string;
    readonly invitationId: string;
    readonly createdAt: Date;
  };
  readonly startedAt: number;
  readonly content: ContentPlan;
  readonly pointsOf: ReadonlyMap<string, string>;
  readonly sectionRows: ReadonlyMap<string, Prisma.TestSectionCreateManyInput>;
  readonly codingBySlug: ReadonlyMap<string, (typeof codingQuestions)[number]>;
  readonly reviewer: string;
}

function addFinishedSession(plan: MutableDeliveryPlan, ctx: FinishedContext): void {
  const { script, finished, base, startedAt, content, reviewer } = ctx;
  const sessionId = base.id;
  const test = script.test;
  const testIdKey = TEST_ID_KEY[test];
  const at = (offsetMin: number): Date => new Date(startedAt + Math.round(offsetMin * MIN));
  const submittedMin = SUBMITTED_AFTER_MIN[test];
  const deadlineAt = at(DURATION_MIN[test]);
  const submittedAt = at(submittedMin);
  const sessionQuestionId = (position: number): string => ID.sessionQuestion(script.key, position);

  // Consent, signed 25 minutes before the start, then the identity check (never a rejection).
  plan.consents.push({
    id: ID.consent(script.key),
    sessionId,
    consentTextId: ID.consentText,
    signedName: ctx.candidateName,
    signedAt: at(-25),
    ip: `203.0.113.${30 + ctx.candidateIndex}`,
    userAgent: USER_AGENT,
  });
  plan.identityChecks.push({
    id: ID.identityCheck(script.key),
    sessionId,
    attempt: 1,
    faceMatchScore: '0.9120',
    modelId: 'synthetic-seed-model',
    threshold: '0.6000',
    livenessPassed: true,
    status: 'PASSED',
    createdAt: at(-14),
  });

  // Sections, in order.
  const limits = SECTION_LIMIT_MIN[test];
  const spans = SECTION_SPANS_MIN[test];
  spans.forEach(([startMin, endMin], index) => {
    const limitMin = limits[index] ?? null;
    const limitDeadline =
      limitMin === null ? deadlineAt : at(Math.min(startMin + limitMin, DURATION_MIN[test]));
    plan.sessionSections.push({
      sessionId,
      sectionId: ID.testSection(testIdKey, index + 1),
      position: index + 1,
      timeLimitMs: limitMin === null ? null : BigInt(limitMin) * 60_000n,
      startedAt: at(startMin),
      deadlineAt: limitDeadline,
      endedAt: at(endMin),
    });
  });

  // Served questions, submissions and scores.
  let totalScore = 0;
  finished.served.forEach((served, index) => {
    const position = index + 1;
    const info = content.questionInfo.get(served.slug);
    if (info === undefined) throw new Error(`Unknown question ${served.slug}.`);
    const testQuestionId = ID.testQuestion(
      testIdKey,
      served.sectionPosition,
      served.testQuestionPosition,
    );
    const points = ctx.pointsOf.get(testQuestionId);
    if (points === undefined) throw new Error(`No test question for ${served.slug}.`);
    const variantId =
      served.variantIndex === null ? null : (info.variantIds[served.variantIndex] ?? null);
    const [sectionStartMin] = spans[served.sectionPosition - 1] ?? [0, 0];
    const row: Prisma.SessionQuestionCreateManyInput = {
      id: sessionQuestionId(position),
      sessionId,
      testQuestionId,
      questionVersionId: info.versionId,
      variantId,
      position,
      points,
    };
    let score = 0;
    const { outcome } = served;
    if (outcome.kind === 'SOLVED') {
      const spec = ctx.codingBySlug.get(served.slug);
      const variant = spec?.variants[served.variantIndex ?? 0];
      if (spec === undefined || variant === undefined)
        throw new Error(`No variant for ${served.slug}.`);
      const code = `${CODE_COMMENT[outcome.language]} Synthetic seed submission.\n${renderSources(spec.referenceTemplates, variant.params)[outcome.language]}`;
      score = Number(points);
      row.score = points;
      row.finalCode = code;
      row.finalLanguage = outcome.language;
      const slots = resolveSlots(spec, served.variantIndex ?? 0);
      const runAt = at(sectionStartMin + 3 + 4 * index);
      const results = (indices: readonly number[]): Prisma.InputJsonArray =>
        indices.map((i) => ({ testCaseId: info.testCaseIds[i] as string, passed: true }));
      const sampleIndices = slots.filter((slot) => !slot.hidden).map((slot) => slot.index);
      const hiddenIndices = slots.filter((slot) => slot.hidden).map((slot) => slot.index);
      plan.submissions.push(
        {
          id: ID.submission(script.key, position, 'RUN'),
          sessionQuestionId: row.id as string,
          kind: 'RUN',
          language: outcome.language,
          sourceCode: code,
          results: results(sampleIndices),
          passed: sampleIndices.length,
          total: sampleIndices.length,
          createdAt: runAt,
        },
        {
          id: ID.submission(script.key, position, 'SUBMIT'),
          sessionQuestionId: row.id as string,
          kind: 'SUBMIT',
          language: outcome.language,
          sourceCode: code,
          results: results(hiddenIndices),
          passed: hiddenIndices.length,
          total: hiddenIndices.length,
          score: points,
          createdAt: new Date(runAt.getTime() + 2 * MIN),
        },
      );
    } else if (outcome.kind === 'NOT_ATTEMPTED') {
      row.score = '0.00';
    } else if (outcome.kind === 'MCQ') {
      const correct = (mcqQuestion.answerSpec.correctOptionIds as string[]).includes(
        outcome.selected,
      );
      score = correct ? Number(points) : 0;
      row.score = score.toFixed(2);
      row.answer = [outcome.selected];
    } else if (outcome.kind === 'SHORT_AUTO') {
      score = Number(points);
      row.score = points;
      row.answer = outcome.text;
    } else {
      // Not an exact match, so it waited for a reviewer, who marked it correct (D-23, TC-099).
      score = Number(points);
      row.score = points;
      row.scoring = 'MANUAL';
      row.scoredById = reviewer;
      row.scoredAt = at(submittedMin + 150);
      row.scoringNote = outcome.note;
      row.answer = outcome.text;
    }
    totalScore += score;
    plan.sessionQuestions.push(row);
  });

  // Events, grouped into signed batches. Client events carry their batch seq; SERVER events do not.
  const seenOfType = new Map<SeededEventType, number>();
  const planned = finished.events.map((event, index) => {
    const rank = seenOfType.get(event.type) ?? 0;
    seenOfType.set(event.type, rank + 1);
    const occurredAt = at(event.atMin);
    const eventCtx: EventContext = { at: occurredAt, sessionQuestionId };
    const row: Omit<Prisma.ProctorEventCreateManyInput, 'id'> = {
      sessionId,
      batchSeq: event.batch,
      type: event.type,
      severity: SEEDED_EVENT_SEVERITY[event.type],
      source: event.batch === null ? 'SERVER' : 'CLIENT',
      occurredAt,
      durationMs: event.durationMs ?? null,
      confidence: event.confidence ?? null,
      payload: event.payload === undefined ? {} : event.payload(eventCtx),
      createdAt: new Date(occurredAt.getTime() + 1000),
    };
    return { event, index, key: eventKey(sessionId, event.type, rank), row };
  });
  for (const item of planned) plan.proctorEvents.push({ key: item.key, row: item.row });

  const batchSeqs = [
    ...new Set(finished.events.flatMap((e) => (e.batch === null ? [] : [e.batch]))),
  ];
  for (const seq of batchSeqs) {
    const members = planned.filter((item) => item.event.batch === seq);
    const last = Math.max(...members.map((item) => (item.row.occurredAt as Date).getTime()));
    plan.proctorEventBatches.push({
      sessionId,
      seq,
      signature: syntheticSignature(`${script.key}:${seq}`),
      eventCount: members.length,
      receivedAt: new Date(last + 2000),
    });
  }

  // Risk score from the stored events (ADR 0005 section 2) and its FR-804 band.
  const score = riskScore(finished.events.map((e) => e.type));
  const band = riskBand(score);

  let reviewCompletedAt: Date | undefined;
  if (finished.review !== undefined) {
    const startedReviewAt = at(submittedMin + 120);
    reviewCompletedAt = at(submittedMin + 180);
    plan.sessionReviews.push({
      id: ID.review(script.key),
      sessionId,
      reviewerId: reviewer,
      verdict: finished.review.verdict,
      notes: finished.review.notes,
      startedAt: startedReviewAt,
      completedAt: reviewCompletedAt,
    });
    for (const item of planned) {
      if (item.event.flag === undefined) continue;
      plan.flagDecisions.push({
        eventKey: item.key,
        row: {
          id: ID.flagDecision(script.key, String(item.index)),
          reviewerId: reviewer,
          decision: item.event.flag.decision,
          note: item.event.flag.note,
          decidedAt: new Date(startedReviewAt.getTime() + (item.index + 1) * MIN),
        },
      });
    }
  }

  // ADR 0004 R-1: the anchor is the latest of submission and verdict time. UNDER_REVIEW holds.
  const anchor =
    script.status === 'UNDER_REVIEW'
      ? null
      : new Date(Math.max(submittedAt.getTime(), reviewCompletedAt?.getTime() ?? 0));

  plan.sessions.push({
    ...base,
    status: script.status === 'UNDER_REVIEW' ? 'UNDER_REVIEW' : 'COMPLETED',
    authEpoch: 1,
    startedAt: at(0),
    deadlineAt,
    submittedAt,
    totalScore: totalScore.toFixed(2),
    riskScore: score,
    riskBand: band,
    lastHeartbeat: submittedAt,
    retentionAnchorAt: anchor,
  });
}
